"""E2E pipeline replay tests — two scenarios using jira-emulator, no real Jira.

Scenario A: New strategy from RFE (no existing STRAT)
Scenario B: Append strategy to existing STRAT
"""
import csv
import json
import os
import subprocess
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))

from artifact_utils import read_frontmatter, read_frontmatter_validated

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SCRIPTS_DIR = os.path.join(PROJECT_ROOT, "scripts")

RFE_DESCRIPTION = (
    "Data scientists need MaaS-hosted model access in MLflow experiments. "
    "This requires a platform-level mechanism to register, discover, and "
    "securely consume MaaS endpoints."
)

STRATEGY_SECTION = """\
## Strategy (AI Generated by Agentic SDLC Pipeline)

### Technical Approach

Implement MLflow AI Gateway integration with RHOAI MaaS component.

### Components Affected

- MLflow integration (rhoai-mlflow)
- MaaS component (rhoai-maas)
- Dashboard (rhoai-dashboard)

### Dependencies

- MLflow 3.12 upgrade (RHAIRFE-1479)
- MaaS provider authentication

### Effort Estimate

M — 2-3 sprints

### Acceptance Criteria

- MaaS endpoints accessible via MLflow experiment runs
- Credentials managed through RHOAI secrets
"""


def _make_env(jira_url):
    env = os.environ.copy()
    env["JIRA_SERVER"] = jira_url
    env["JIRA_USER"] = "admin"
    env["JIRA_TOKEN"] = "admin"
    return env


def _run_script(script_name, args, env, cwd=PROJECT_ROOT):
    return subprocess.run(
        [sys.executable, os.path.join(SCRIPTS_DIR, script_name)] + args,
        capture_output=True, text=True, env=env, cwd=cwd,
    )


def _write_scores_csv(path, rows):
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "ID", "Feasibility", "Testability", "Scope", "Architecture",
            "Total", "Verdict", "Needs_Attention",
        ])
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


class TestScenarioA:
    """New strategy from RFE — no existing STRAT."""

    def test_full_pipeline_new_strategy(self, jira, art_dir):
        env = _make_env(jira.url)
        strat_tasks = art_dir / "artifacts" / "strat-tasks"
        strat_reviews = art_dir / "artifacts" / "strat-reviews"
        strat_originals = art_dir / "artifacts" / "strat-originals"

        # 1. Seed emulator with RFE
        jira.create(
            "RHAIRFE-2000",
            "Access to MaaS-Hosted Models",
            RFE_DESCRIPTION,
            labels=["strat-creator-3.5", "rfe-creator-autofix-rubric-pass"],
        )

        # 2. Verify no existing STRAT
        result = _run_script(
            "find_strat_for_rfe.py",
            ["RHAIRFE-2000", "--json"], env,
        )
        assert result.returncode == 1
        assert json.loads(result.stdout) == []

        # 3. Clone RFE to RHAISTRAT
        result = _run_script(
            "clone_issue.py",
            ["RHAIRFE-2000", "--target-project", "RHAISTRAT",
             "--issue-type", "Feature"], env,
        )
        assert result.returncode == 0
        strat_key = result.stdout.strip()
        assert strat_key.startswith("RHAISTRAT-")

        # Verify Cloners link created
        result = _run_script(
            "find_strat_for_rfe.py",
            ["RHAIRFE-2000", "--json"], env,
        )
        assert result.returncode == 0
        strats = json.loads(result.stdout)
        assert len(strats) >= 1
        assert any(s["key"] == strat_key for s in strats)

        # 4. Create strategy stub with frontmatter
        stub_path = strat_tasks / f"{strat_key}.md"
        result = _run_script(
            "frontmatter.py",
            ["set", str(stub_path),
             f"strat_id={strat_key}",
             "title=Access to MaaS-Hosted Models",
             "source_rfe=RHAIRFE-2000",
             f"jira_key={strat_key}",
             "priority=Major",
             "status=Draft"],
            env, cwd=str(art_dir),
        )
        assert result.returncode == 0
        assert stub_path.exists()

        # Verify frontmatter
        data, _ = read_frontmatter_validated(str(stub_path), "strat-task")
        assert data["strat_id"] == strat_key
        assert data["status"] == "Draft"
        assert data["source_rfe"] == "RHAIRFE-2000"

        # 5. Simulate refinement: add strategy section
        with open(stub_path, "a", encoding="utf-8") as f:
            f.write("\n## Business Need (from RFE)\n\n")
            f.write(RFE_DESCRIPTION + "\n\n")
            f.write(STRATEGY_SECTION)

        # Update status to Refined
        result = _run_script(
            "frontmatter.py",
            ["set", str(stub_path), "status=Refined"],
            env, cwd=str(art_dir),
        )
        assert result.returncode == 0

        # 6. Push strategy to emulator
        result = _run_script(
            "push_strategy.py",
            [strat_key, str(stub_path)], env,
        )
        assert result.returncode == 0

        # Verify it landed in Jira
        issue = jira.get(strat_key)
        assert issue is not None

        # 7. Apply scores
        scores_csv = art_dir / "scores.csv"
        _write_scores_csv(str(scores_csv), [{
            "ID": strat_key,
            "Feasibility": "2",
            "Testability": "1",
            "Scope": "2",
            "Architecture": "1",
            "Total": "6",
            "Verdict": "APPROVE",
            "Needs_Attention": "false",
        }])

        result = _run_script(
            "apply_scores.py",
            [str(scores_csv), "--review-dir", str(strat_reviews)],
            env, cwd=str(art_dir),
        )
        assert result.returncode == 0

        # 8. Verify review file
        review_path = strat_reviews / f"{strat_key}-review.md"
        assert review_path.exists()

        data, body = read_frontmatter_validated(str(review_path), "strat-review")
        assert data["strat_id"] == strat_key
        assert data["recommendation"] == "approve"
        assert data["needs_attention"] is False
        assert data["scores"]["total"] == 6
        assert data["scores"]["feasibility"] == 2
        assert data["scores"]["testability"] == 1

        # Verify labels computed correctly
        from artifact_utils import compute_strat_labels
        labels = compute_strat_labels("Refined", data["recommendation"])
        assert "strat-creator-rubric-pass" in labels
        assert "strat-creator-needs-attention" not in labels


class TestScenarioB:
    """Append strategy to existing STRAT."""

    def test_full_pipeline_existing_strat(self, jira, art_dir):
        env = _make_env(jira.url)
        strat_tasks = art_dir / "artifacts" / "strat-tasks"
        strat_reviews = art_dir / "artifacts" / "strat-reviews"

        # 1. Seed emulator with RFE and existing RHAISTRAT
        jira.create(
            "RHAIRFE-3000",
            "Existing RFE for STRAT append test",
            "Business Need description for the RFE.",
        )
        jira.create(
            "RHAISTRAT-5000",
            "Existing RFE for STRAT append test",
            "## Business Need (from RFE)\n\nBusiness Need description for the RFE.",
        )

        # Create Cloners link
        jira.request("POST", "/rest/api/3/issueLink", {
            "type": {"name": "Cloners"},
            "inwardIssue": {"key": "RHAIRFE-3000"},
            "outwardIssue": {"key": "RHAISTRAT-5000"},
        })

        # 2. Verify existing STRAT found
        result = _run_script(
            "find_strat_for_rfe.py",
            ["RHAIRFE-3000", "--json"], env,
        )
        assert result.returncode == 0
        strats = json.loads(result.stdout)
        assert len(strats) >= 1
        strat_key = "RHAISTRAT-5000"
        assert any(s["key"] == strat_key for s in strats)

        # 3. Write local strategy file with Strategy section
        local_file = strat_tasks / f"{strat_key}.md"
        content = f"""\
---
strat_id: {strat_key}
title: Existing RFE for STRAT append test
source_rfe: RHAIRFE-3000
jira_key: {strat_key}
priority: Major
status: Refined
---
## Business Need (from RFE)

Business Need description for the RFE.

{STRATEGY_SECTION}
"""
        local_file.write_text(content)

        # 4. Push strategy — appends to existing description
        result = _run_script(
            "push_strategy.py",
            [strat_key, str(local_file)], env,
        )
        assert result.returncode == 0

        # Verify strategy was pushed
        issue = jira.get(strat_key)
        assert issue is not None

        # Verify backup was created
        backup = art_dir / "artifacts" / "strat-originals" / f"{strat_key}-pre-push.md"
        assert backup.exists()
        backup_content = backup.read_text()
        assert "Business Need" in backup_content

        # 5. Apply different scores — REVISE verdict
        scores_csv = art_dir / "scores.csv"
        _write_scores_csv(str(scores_csv), [{
            "ID": strat_key,
            "Feasibility": "1",
            "Testability": "1",
            "Scope": "1",
            "Architecture": "1",
            "Total": "4",
            "Verdict": "REVISE",
            "Needs_Attention": "true",
        }])

        result = _run_script(
            "apply_scores.py",
            [str(scores_csv), "--review-dir", str(strat_reviews)],
            env, cwd=str(art_dir),
        )
        assert result.returncode == 0

        # Verify review shows REVISE with needs_attention
        review_path = strat_reviews / f"{strat_key}-review.md"
        assert review_path.exists()

        data, _ = read_frontmatter_validated(str(review_path), "strat-review")
        assert data["recommendation"] == "revise"
        assert data["needs_attention"] is True
        assert data["scores"]["total"] == 4

        # Verify labels
        from artifact_utils import compute_strat_labels
        labels = compute_strat_labels("Refined", data["recommendation"])
        assert "strat-creator-needs-attention" in labels
        assert "strat-creator-rubric-pass" not in labels

    def test_score_update_after_revision(self, jira, art_dir):
        """After a REVISE verdict, re-score with better scores → APPROVE."""
        env = _make_env(jira.url)
        strat_reviews = art_dir / "artifacts" / "strat-reviews"
        strat_key = "STRAT-999"

        # Create initial review with REVISE
        scores_csv = art_dir / "scores1.csv"
        _write_scores_csv(str(scores_csv), [{
            "ID": strat_key,
            "Feasibility": "0",
            "Testability": "1",
            "Scope": "1",
            "Architecture": "1",
            "Total": "3",
            "Verdict": "REVISE",
            "Needs_Attention": "true",
        }])
        result = _run_script(
            "apply_scores.py",
            [str(scores_csv), "--review-dir", str(strat_reviews)],
            env, cwd=str(art_dir),
        )
        assert result.returncode == 0

        data, _ = read_frontmatter_validated(
            str(strat_reviews / f"{strat_key}-review.md"), "strat-review")
        assert data["recommendation"] == "revise"
        assert data["needs_attention"] is True

        # Re-score after revision → APPROVE
        scores_csv2 = art_dir / "scores2.csv"
        _write_scores_csv(str(scores_csv2), [{
            "ID": strat_key,
            "Feasibility": "2",
            "Testability": "2",
            "Scope": "1",
            "Architecture": "2",
            "Total": "7",
            "Verdict": "APPROVE",
            "Needs_Attention": "false",
        }])
        result = _run_script(
            "apply_scores.py",
            [str(scores_csv2), "--review-dir", str(strat_reviews)],
            env, cwd=str(art_dir),
        )
        assert result.returncode == 0

        data, _ = read_frontmatter_validated(
            str(strat_reviews / f"{strat_key}-review.md"), "strat-review")
        assert data["recommendation"] == "approve"
        assert data["needs_attention"] is False
        assert data["scores"]["total"] == 7
