import os
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))

from strategy_history import (
    find_latest_version,
    extract_strategy_section,
    split_subsections,
    word_diff,
    has_changes,
    diff_to_html,
    generate_diff_html,
    snapshot,
    save,
    STRATEGY_HEADING,
)
from artifact_utils import read_frontmatter


SAMPLE_FRONTMATTER = """\
---
strat_id: RHAISTRAT-100
title: Test Strategy
source_rfe: RHAIRFE-200
priority: Major
status: Refined
workflow: local
---
"""

SAMPLE_STRATEGY_V1 = """\
## Strategy (AI Generated by Agentic SDLC Pipeline)

### TL;DR

Implement feature X using component A.

### Technical Approach

Use REST APIs to integrate with service B.
Deploy on OpenShift using standard operators.

### Affected Components

- Component A
- Component B

### Effort Estimate

Medium (2-3 sprints)
"""

SAMPLE_STRATEGY_V2 = """\
## Strategy (AI Generated by Agentic SDLC Pipeline)

### TL;DR

Implement feature X using component A and component C.

### Technical Approach

Use gRPC APIs to integrate with service B.
Deploy on OpenShift using standard operators.

### Affected Components

- Component A
- Component B
- Component C

### Effort Estimate

Medium (2-3 sprints)
"""


def _make_strategy_file(path, strategy_body, frontmatter=SAMPLE_FRONTMATTER):
    """Write a strategy file with frontmatter and body."""
    business_need = "## Business Need (from RFE)\n\nWe need feature X.\n\n"
    content = frontmatter + business_need + strategy_body
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    return content


class TestVersionDiscovery:

    def test_returns_neg_one_for_empty_dir(self, tmp_path):
        assert find_latest_version(str(tmp_path)) == -1

    def test_returns_neg_one_for_nonexistent_dir(self, tmp_path):
        assert find_latest_version(str(tmp_path / "nope")) == -1

    def test_finds_single_version(self, tmp_path):
        (tmp_path / "v1.md").write_text("content")
        assert find_latest_version(str(tmp_path)) == 1

    def test_finds_highest_version(self, tmp_path):
        for i in [1, 2, 5, 3]:
            (tmp_path / f"v{i}.md").write_text("content")
        assert find_latest_version(str(tmp_path)) == 5

    def test_ignores_non_version_files(self, tmp_path):
        (tmp_path / "v1.md").write_text("content")
        (tmp_path / "v1-to-v2.html").write_text("diff")
        (tmp_path / "notes.md").write_text("notes")
        assert find_latest_version(str(tmp_path)) == 1


class TestExtractStrategySection:

    def test_extracts_strategy(self):
        content = (
            "## Business Need\n\nSome need.\n\n"
            + SAMPLE_STRATEGY_V1
            + "\n## Staff Engineer / SME Input\n\nNotes here.\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert "### TL;DR" in result
        assert "### Technical Approach" in result
        assert "Staff Engineer" not in result
        assert "Business Need" not in result

    def test_returns_none_when_missing(self):
        content = "## Business Need\n\nJust a need.\n"
        assert extract_strategy_section(content) is None


class TestSubsectionExtraction:

    def test_splits_into_subsections(self):
        result = split_subsections(SAMPLE_STRATEGY_V1)
        headings = [h for h, _ in result]
        assert STRATEGY_HEADING in headings
        assert "### TL;DR" in headings
        assert "### Technical Approach" in headings
        assert "### Affected Components" in headings
        assert "### Effort Estimate" in headings

    def test_preserves_body_content(self):
        result = split_subsections(SAMPLE_STRATEGY_V1)
        sub_map = {h: b for h, b in result}
        assert "component A" in sub_map["### TL;DR"]
        assert "REST APIs" in sub_map["### Technical Approach"]

    def test_handles_empty_strategy(self):
        result = split_subsections("")
        assert result == []

    def test_handles_heading_only(self):
        result = split_subsections(STRATEGY_HEADING)
        assert len(result) == 1
        assert result[0][0] == STRATEGY_HEADING
        assert result[0][1] == ""


class TestWordLevelDiff:

    def test_identical_text_no_changes(self):
        diffs = word_diff("hello world", "hello world")
        assert not has_changes(diffs)

    def test_detects_word_changes(self):
        diffs = word_diff("Use REST APIs", "Use gRPC APIs")
        assert has_changes(diffs)
        ops = [op for op, _ in diffs]
        assert -1 in ops
        assert 1 in ops

    def test_detects_additions(self):
        diffs = word_diff("Component A", "Component A and B")
        assert has_changes(diffs)

    def test_detects_deletions(self):
        diffs = word_diff("Component A and B", "Component A")
        assert has_changes(diffs)

    def test_empty_to_content(self):
        diffs = word_diff("", "new content")
        assert has_changes(diffs)

    def test_content_to_empty(self):
        diffs = word_diff("old content", "")
        assert has_changes(diffs)


class TestDiffToHtml:

    def test_equal_text_no_tags(self):
        html = diff_to_html([(0, "hello")])
        assert html == "hello"
        assert "<del" not in html
        assert "<ins" not in html

    def test_delete_gets_del_tag(self):
        html = diff_to_html([(-1, "removed")])
        assert '<del class="diff-del">removed</del>' in html

    def test_insert_gets_ins_tag(self):
        html = diff_to_html([(1, "added")])
        assert '<ins class="diff-ins">added</ins>' in html

    def test_escapes_html_entities(self):
        html = diff_to_html([(0, "<script>")])
        assert "&lt;script&gt;" in html
        assert "<script>" not in html

    def test_mixed_diff(self):
        html = diff_to_html([(0, "Use "), (-1, "REST"), (1, "gRPC"), (0, " APIs")])
        assert "Use " in html
        assert '<del class="diff-del">REST</del>' in html
        assert '<ins class="diff-ins">gRPC</ins>' in html
        assert " APIs" in html


class TestHtmlGeneration:

    def test_generates_valid_html(self):
        content_v1 = SAMPLE_FRONTMATTER + SAMPLE_STRATEGY_V1
        content_v2 = SAMPLE_FRONTMATTER + SAMPLE_STRATEGY_V2
        html = generate_diff_html("RHAISTRAT-100", "v0", "v1", content_v1, content_v2)
        assert "<!DOCTYPE html>" in html
        assert "RHAISTRAT-100" in html
        assert "v0" in html
        assert "v1" in html

    def test_changed_sections_expanded(self):
        content_v1 = SAMPLE_FRONTMATTER + SAMPLE_STRATEGY_V1
        content_v2 = SAMPLE_FRONTMATTER + SAMPLE_STRATEGY_V2
        html = generate_diff_html("RHAISTRAT-100", "v0", "v1", content_v1, content_v2)
        assert "diff-del" in html
        assert "diff-ins" in html

    def test_unchanged_sections_collapsed(self):
        content_v1 = SAMPLE_FRONTMATTER + SAMPLE_STRATEGY_V1
        content_v2 = SAMPLE_FRONTMATTER + SAMPLE_STRATEGY_V2
        html = generate_diff_html("RHAISTRAT-100", "v0", "v1", content_v1, content_v2)
        assert "no changes" in html.lower()
        assert "collapsed" in html

    def test_toc_present(self):
        content_v1 = SAMPLE_FRONTMATTER + SAMPLE_STRATEGY_V1
        content_v2 = SAMPLE_FRONTMATTER + SAMPLE_STRATEGY_V2
        html = generate_diff_html("RHAISTRAT-100", "v0", "v1", content_v1, content_v2)
        assert "Sections" in html
        assert "toc-changed" in html
        assert "toc-unchanged" in html

    def test_self_contained_no_external_deps(self):
        content_v1 = SAMPLE_FRONTMATTER + SAMPLE_STRATEGY_V1
        content_v2 = SAMPLE_FRONTMATTER + SAMPLE_STRATEGY_V2
        html = generate_diff_html("RHAISTRAT-100", "v0", "v1", content_v1, content_v2)
        assert "<style>" in html
        assert "<script>" in html
        assert 'href="http' not in html
        assert 'src="http' not in html


class TestSnapshotCommand:

    def test_snapshot_creates_staging_file(self, tmp_path):
        strat_dir = tmp_path / "local" / "strat-tasks"
        strat_dir.mkdir(parents=True)
        strat_path = str(strat_dir / "RHAISTRAT-100.md")
        _make_strategy_file(strat_path, SAMPLE_STRATEGY_V1)

        result = snapshot(strat_path)
        assert result == 0

        history_dir = tmp_path / "local" / "strat-history" / "RHAISTRAT-100"
        assert (history_dir / ".pre-refine.md").exists()

    def test_snapshot_nonexistent_file_returns_error(self):
        result = snapshot("/nonexistent/path/RHAISTRAT-999.md")
        assert result == 1


class TestSaveCommand:

    def test_pull_creates_v0_baseline(self, tmp_path):
        """Pull (save without snapshot) creates v0 baseline — no diff."""
        strat_dir = tmp_path / "local" / "strat-tasks"
        strat_dir.mkdir(parents=True)
        strat_path = str(strat_dir / "RHAISTRAT-100.md")
        _make_strategy_file(strat_path, SAMPLE_STRATEGY_V1)

        result = save(strat_path)
        assert result == 0

        history_dir = tmp_path / "local" / "strat-history" / "RHAISTRAT-100"
        assert (history_dir / "v0.md").exists()
        assert not list(history_dir.glob("*.html"))

    def test_first_refine_after_pull_creates_v1_with_diff(self, tmp_path):
        """Pull creates v0, first refine creates v1 with v0-to-v1 diff."""
        strat_dir = tmp_path / "local" / "strat-tasks"
        strat_dir.mkdir(parents=True)
        strat_path = str(strat_dir / "RHAISTRAT-100.md")

        _make_strategy_file(strat_path, SAMPLE_STRATEGY_V1)
        save(strat_path)  # pull → v0

        snapshot(strat_path)  # refine pre-snapshot
        _make_strategy_file(strat_path, SAMPLE_STRATEGY_V2)
        result = save(strat_path)  # refine post-save → v1
        assert result == 0

        history_dir = tmp_path / "local" / "strat-history" / "RHAISTRAT-100"
        assert (history_dir / "v0.md").exists()
        assert (history_dir / "v1.md").exists()
        assert (history_dir / "v0-to-v1.html").exists()
        assert not (history_dir / ".pre-refine.md").exists()

        data, _ = read_frontmatter(strat_path)
        assert data["latest_diff"] == "strat-history/RHAISTRAT-100/v0-to-v1.html"

    def test_second_refine_creates_v2_diff(self, tmp_path):
        strat_dir = tmp_path / "local" / "strat-tasks"
        strat_dir.mkdir(parents=True)
        strat_path = str(strat_dir / "RHAISTRAT-100.md")

        _make_strategy_file(strat_path, SAMPLE_STRATEGY_V1)
        save(strat_path)  # pull → v0

        snapshot(strat_path)  # first refine
        _make_strategy_file(strat_path, SAMPLE_STRATEGY_V2)
        save(strat_path)  # → v1

        snapshot(strat_path)  # second refine
        v3_strategy = SAMPLE_STRATEGY_V1.replace("Medium (2-3 sprints)", "Large (4-5 sprints)")
        _make_strategy_file(strat_path, v3_strategy)
        save(strat_path)  # → v2

        history_dir = tmp_path / "local" / "strat-history" / "RHAISTRAT-100"
        assert (history_dir / "v2.md").exists()
        assert (history_dir / "v1-to-v2.html").exists()

        data, _ = read_frontmatter(strat_path)
        assert data["latest_diff"] == "strat-history/RHAISTRAT-100/v1-to-v2.html"

    def test_save_without_snapshot_falls_back_to_prev_version(self, tmp_path):
        """If snapshot wasn't called, save falls back to diffing against previous version."""
        strat_dir = tmp_path / "local" / "strat-tasks"
        strat_dir.mkdir(parents=True)
        strat_path = str(strat_dir / "RHAISTRAT-100.md")

        _make_strategy_file(strat_path, SAMPLE_STRATEGY_V1)
        save(strat_path)  # v0

        _make_strategy_file(strat_path, SAMPLE_STRATEGY_V2)
        result = save(strat_path)  # v1, diffs against v0
        assert result == 0

        history_dir = tmp_path / "local" / "strat-history" / "RHAISTRAT-100"
        assert (history_dir / "v0-to-v1.html").exists()

    def test_diff_html_contains_actual_changes(self, tmp_path):
        strat_dir = tmp_path / "local" / "strat-tasks"
        strat_dir.mkdir(parents=True)
        strat_path = str(strat_dir / "RHAISTRAT-100.md")

        _make_strategy_file(strat_path, SAMPLE_STRATEGY_V1)
        save(strat_path)  # pull → v0

        snapshot(strat_path)  # refine
        _make_strategy_file(strat_path, SAMPLE_STRATEGY_V2)
        save(strat_path)  # → v1

        diff_path = tmp_path / "local" / "strat-history" / "RHAISTRAT-100" / "v0-to-v1.html"
        html = diff_path.read_text()
        assert "REST" in html
        assert "gRPC" in html


class TestFirstRun:

    def test_pull_then_refine_full_flow(self, tmp_path):
        strat_dir = tmp_path / "local" / "strat-tasks"
        strat_dir.mkdir(parents=True)
        strat_path = str(strat_dir / "RHAISTRAT-100.md")

        _make_strategy_file(strat_path, SAMPLE_STRATEGY_V1)
        save(strat_path)  # pull → v0

        snapshot(strat_path)
        _make_strategy_file(strat_path, SAMPLE_STRATEGY_V2)
        save(strat_path)  # refine → v1

        history_dir = tmp_path / "local" / "strat-history" / "RHAISTRAT-100"
        assert (history_dir / "v0.md").exists()
        assert (history_dir / "v1.md").exists()
        assert (history_dir / "v0-to-v1.html").exists()

    def test_nonexistent_file_returns_error(self):
        result = save("/nonexistent/path/RHAISTRAT-999.md")
        assert result == 1


class TestIdempotency:

    def test_snapshot_save_no_real_changes(self, tmp_path):
        """Snapshot + save where refine didn't change anything — diff shows no changes."""
        strat_dir = tmp_path / "local" / "strat-tasks"
        strat_dir.mkdir(parents=True)
        strat_path = str(strat_dir / "RHAISTRAT-100.md")
        _make_strategy_file(strat_path, SAMPLE_STRATEGY_V1)

        save(strat_path)  # pull → v0
        snapshot(strat_path)
        save(strat_path)  # refine (no changes) → v1

        history_dir = tmp_path / "local" / "strat-history" / "RHAISTRAT-100"
        diff_path = history_dir / "v0-to-v1.html"
        assert diff_path.exists()
        html = diff_path.read_text()
        assert "<del " not in html
        assert "<ins " not in html
