"""Integration tests for pull_strategy.py against jira-emulator."""
import json
import os
import subprocess
import sys
import tempfile

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))

from artifact_utils import read_frontmatter
from jira_utils import (
    markdown_to_adf,
    add_attachment,
    build_rfe_reference,
    RFE_REFERENCE_MARKER,
    BUSINESS_NEED_HEADING,
)

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SCRIPT = os.path.join(PROJECT_ROOT, "scripts", "pull_strategy.py")


def _env(jira):
    return {
        **os.environ,
        "JIRA_SERVER": jira.url,
        "JIRA_USER": "admin",
        "JIRA_TOKEN": "admin",
    }


def _run(jira, strat_key, local_dir, extra_args=None):
    cmd = [sys.executable, SCRIPT, strat_key, "--local-dir", str(local_dir)]
    if extra_args:
        cmd.extend(extra_args)
    return subprocess.run(
        cmd,
        env=_env(jira),
        capture_output=True,
        text=True,
        cwd=PROJECT_ROOT,
    )


def _setup_strat_with_rfe(jira, strat_key, rfe_key, labels=None):
    """Create a STRAT issue linked to an RFE via Cloners."""
    desc_md = (
        "## Business Need (from RFE)\n\n"
        "Users need GPU sharing.\n\n"
        "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
        "### Technical Approach\n\n"
        "Use MIG profiles for GPU time-slicing.\n"
    )
    jira.create(strat_key, "GPU time-slicing strategy", desc_md,
                labels=labels or [])
    jira.create(rfe_key, "GPU sharing RFE",
                "Users need cost-efficient GPU sharing.")

    jira.request("POST", "/rest/api/3/issueLink", {
        "type": {"name": "Cloners"},
        "inwardIssue": {"key": rfe_key},
        "outwardIssue": {"key": strat_key},
    })


class TestPullWithRubricPass:

    def test_pulls_strategy_file(self, jira, tmp_path):
        _setup_strat_with_rfe(jira, "RHAISTRAT-2000", "RHAIRFE-3000",
                              labels=["strat-creator-rubric-pass"])

        local_dir = tmp_path / "local"
        result = _run(jira, "RHAISTRAT-2000", local_dir)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        strat_path = local_dir / "strat-tasks" / "RHAISTRAT-2000.md"
        assert strat_path.exists()

        data, body = read_frontmatter(str(strat_path))
        assert data["strat_id"] == "RHAISTRAT-2000"
        assert data["workflow"] == "local"
        assert data["source_rfe"] == "RHAIRFE-3000"
        assert "GPU time-slicing" in body

    def test_pulls_rfe_original(self, jira, tmp_path):
        _setup_strat_with_rfe(jira, "RHAISTRAT-2001", "RHAIRFE-3001",
                              labels=["strat-creator-rubric-pass"])

        local_dir = tmp_path / "local"
        result = _run(jira, "RHAISTRAT-2001", local_dir)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        rfe_path = local_dir / "strat-originals" / "RHAIRFE-3001.md"
        assert rfe_path.exists()
        assert "GPU sharing" in rfe_path.read_text()

    def test_frontmatter_has_correct_fields(self, jira, tmp_path):
        _setup_strat_with_rfe(jira, "RHAISTRAT-2002", "RHAIRFE-3002",
                              labels=["strat-creator-rubric-pass"])

        local_dir = tmp_path / "local"
        _run(jira, "RHAISTRAT-2002", local_dir)

        strat_path = local_dir / "strat-tasks" / "RHAISTRAT-2002.md"
        data, _ = read_frontmatter(str(strat_path))
        assert data["strat_id"] == "RHAISTRAT-2002"
        assert data["jira_key"] == "RHAISTRAT-2002"
        assert data["source_rfe"] == "RHAIRFE-3002"
        assert data["status"] == "Refined"
        assert data["workflow"] == "local"
        assert data["title"] == "GPU time-slicing strategy"


class TestPullWithNeedsAttention:

    def test_pulls_strategy_with_needs_attention(self, jira, tmp_path):
        _setup_strat_with_rfe(jira, "RHAISTRAT-2010", "RHAIRFE-3010",
                              labels=["strat-creator-needs-attention"])

        local_dir = tmp_path / "local"
        result = _run(jira, "RHAISTRAT-2010", local_dir)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        strat_path = local_dir / "strat-tasks" / "RHAISTRAT-2010.md"
        assert strat_path.exists()
        data, _ = read_frontmatter(str(strat_path))
        assert data["workflow"] == "local"


class TestPullGateChecks:

    def test_rejects_strategy_without_post_ci_labels(self, jira, tmp_path):
        jira.create("RHAISTRAT-2020", "No labels strategy", "Some content")

        local_dir = tmp_path / "local"
        result = _run(jira, "RHAISTRAT-2020", local_dir)
        assert result.returncode == 1
        assert "post-CI label" in result.stderr

        strat_path = local_dir / "strat-tasks" / "RHAISTRAT-2020.md"
        assert not strat_path.exists()

    def test_rejects_strategy_with_wrong_labels(self, jira, tmp_path):
        jira.create("RHAISTRAT-2021", "Wrong labels", "Content",
                    labels=["strat-creator-auto-created"])

        local_dir = tmp_path / "local"
        result = _run(jira, "RHAISTRAT-2021", local_dir)
        assert result.returncode == 1

    def test_rejects_non_rhaistrat_key(self, jira, tmp_path):
        local_dir = tmp_path / "local"
        result = _run(jira, "RHAIRFE-9999", local_dir)
        assert result.returncode == 1
        assert "RHAISTRAT-NNNN" in result.stderr


class TestPullMissingCredentials:

    def test_exits_code_2_without_env_vars(self, tmp_path):
        env = {k: v for k, v in os.environ.items()
               if k not in ("JIRA_SERVER", "JIRA_USER", "JIRA_TOKEN")}
        local_dir = tmp_path / "local"
        result = subprocess.run(
            [sys.executable, SCRIPT, "RHAISTRAT-9999",
             "--local-dir", str(local_dir)],
            env=env,
            capture_output=True,
            text=True,
            cwd=PROJECT_ROOT,
        )
        assert result.returncode == 2


class TestPullReviewComment:

    def test_extracts_review_comment(self, jira, tmp_path):
        _setup_strat_with_rfe(jira, "RHAISTRAT-2030", "RHAIRFE-3030",
                              labels=["strat-creator-rubric-pass"])

        review_md = (
            "*[Strat Creator]* Strategy Review — APPROVE (Score: 7/8)\n\n"
            "| Criterion | Score |\n"
            "| --- | --- |\n"
            "| Feasibility | 2/2 |\n"
        )
        review_adf = markdown_to_adf(review_md)
        jira.request("POST", f"/rest/api/3/issue/RHAISTRAT-2030/comment",
                     {"body": review_adf})

        local_dir = tmp_path / "local"
        result = _run(jira, "RHAISTRAT-2030", local_dir)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        review_path = local_dir / "strat-reviews" / "RHAISTRAT-2030-review-summary.md"
        assert review_path.exists()
        content = review_path.read_text()
        assert "[Strat Creator]" in content
        assert "APPROVE" in content


STRATEGY_HEADING = "## Strategy (AI Generated by Agentic SDLC Pipeline)"


def _upload_strategy_attachment(jira, strat_key, strategy_content):
    """Upload a strategy markdown file as an attachment."""
    with tempfile.NamedTemporaryFile(
            mode="w", suffix=".md", delete=False, encoding="utf-8") as f:
        f.write(strategy_content)
        tmp_path = f.name
    try:
        add_attachment(jira.url, "admin", "admin", strat_key,
                       tmp_path, filename=f"{strat_key}-strategy.md")
    finally:
        os.unlink(tmp_path)


class TestPullWithStrategyAttachment:

    def test_pulls_strategy_from_attachment(self, jira, tmp_path):
        stub_desc = (
            "## Business Need (from RFE)\n\n"
            "Users need GPU sharing.\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "> **Note:** The full strategy exceeds Jira's description size "
            "limit and is stored as an attachment: "
            "`RHAISTRAT-2040-strategy.md`.\n\n"
            "### TL;DR\n\n"
            "Enable GPU sharing via MIG.\n"
        )
        jira.create("RHAISTRAT-2040", "Attachment pull test", stub_desc,
                     labels=["strat-creator-rubric-pass"])
        jira.create("RHAIRFE-3040", "GPU sharing RFE",
                     "Users need cost-efficient GPU sharing.")
        jira.request("POST", "/rest/api/3/issueLink", {
            "type": {"name": "Cloners"},
            "inwardIssue": {"key": "RHAIRFE-3040"},
            "outwardIssue": {"key": "RHAISTRAT-2040"},
        })

        full_strategy = (
            f"{STRATEGY_HEADING}\n\n"
            "### TL;DR\n\n"
            "Enable GPU sharing via MIG.\n\n"
            "### Technical Approach\n\n"
            "Use NVIDIA device plugin with MIG profiles.\n\n"
            "### Affected Components\n\n"
            "| Component | Change |\n"
            "| --- | --- |\n"
            "| nvidia-plugin | Add MIG support |\n"
        )
        _upload_strategy_attachment(jira, "RHAISTRAT-2040", full_strategy)

        local_dir = tmp_path / "local"
        result = _run(jira, "RHAISTRAT-2040", local_dir)
        assert result.returncode == 0, f"stderr: {result.stderr}"
        assert "attachment" in result.stdout.lower()

        strat_path = local_dir / "strat-tasks" / "RHAISTRAT-2040.md"
        content = strat_path.read_text()
        assert "Business Need" in content
        assert "Users need GPU sharing" in content
        assert "### Technical Approach" in content
        assert "NVIDIA device plugin with MIG profiles" in content
        assert "### Affected Components" in content

    def test_pulls_from_description_when_no_attachment(self, jira, tmp_path):
        desc = (
            "## Business Need (from RFE)\n\n"
            "Users need GPU sharing.\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "### Technical Approach\n\n"
            "Use MIG profiles.\n"
        )
        jira.create("RHAISTRAT-2041", "No attachment", desc,
                     labels=["strat-creator-rubric-pass"])
        jira.create("RHAIRFE-3041", "GPU RFE", "GPU sharing needed.")
        jira.request("POST", "/rest/api/3/issueLink", {
            "type": {"name": "Cloners"},
            "inwardIssue": {"key": "RHAIRFE-3041"},
            "outwardIssue": {"key": "RHAISTRAT-2041"},
        })

        local_dir = tmp_path / "local"
        result = _run(jira, "RHAISTRAT-2041", local_dir)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        strat_path = local_dir / "strat-tasks" / "RHAISTRAT-2041.md"
        content = strat_path.read_text()
        assert "Technical Approach" in content
        assert "Use MIG profiles" in content

    def test_round_trip_push_pull(self, jira, tmp_path):
        """Push a large strategy (goes to attachment), pull it back,
        verify the local file has the full strategy content."""
        jira.create("RHAISTRAT-2042", "Round trip",
                     "## Business Need\n\nContext for round-trip test.",
                     labels=["strat-creator-rubric-pass"])
        jira.create("RHAIRFE-3042", "RFE for round trip", "Some RFE.")
        jira.request("POST", "/rest/api/3/issueLink", {
            "type": {"name": "Cloners"},
            "inwardIssue": {"key": "RHAIRFE-3042"},
            "outwardIssue": {"key": "RHAISTRAT-2042"},
        })

        push_script = os.path.join(PROJECT_ROOT, "scripts", "push_strategy.py")
        push_dir = tmp_path / "push-workspace" / "artifacts"
        (push_dir / "strat-tasks").mkdir(parents=True)
        (push_dir / "strat-originals").mkdir(parents=True)

        lines = [f"{STRATEGY_HEADING}\n", "### TL;DR\n",
                 "Round-trip test summary.\n", "### Technical Approach\n"]
        while sum(len(l) for l in lines) < 25000:
            lines.append(
                "Detailed paragraph about GPU time-slicing implementation "
                "approach using NVIDIA MIG profiles and device plugins.\n\n")
        large_strategy = "\n".join(lines)

        push_file = push_dir / "strat-tasks" / "RHAISTRAT-2042.md"
        push_file.write_text(large_strategy)

        push_env = {
            **os.environ,
            "JIRA_SERVER": jira.url,
            "JIRA_USER": "admin",
            "JIRA_TOKEN": "admin",
        }
        push_result = subprocess.run(
            [sys.executable, push_script, "RHAISTRAT-2042", str(push_file)],
            env=push_env, capture_output=True, text=True, cwd=PROJECT_ROOT)
        assert push_result.returncode == 0, f"push stderr: {push_result.stderr}"

        local_dir = tmp_path / "local"
        pull_result = _run(jira, "RHAISTRAT-2042", local_dir)
        assert pull_result.returncode == 0, f"pull stderr: {pull_result.stderr}"

        pulled_path = local_dir / "strat-tasks" / "RHAISTRAT-2042.md"
        pulled_content = pulled_path.read_text()
        assert "### Technical Approach" in pulled_content
        assert "Round-trip test summary" in pulled_content
        assert "GPU time-slicing" in pulled_content


class TestPullRfeReconstruction:

    def test_reconstructs_business_need_from_reference(self, jira, tmp_path):
        """When Jira description has a reference link instead of full RFE,
        pull reconstructs the Business Need from the linked RHAIRFE."""
        rfe_ref = build_rfe_reference("RHAIRFE-3050", jira.url)
        desc = (
            f"{rfe_ref}\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "### Technical Approach\n\n"
            "Use MIG profiles.\n"
        )
        jira.create("RHAISTRAT-2050", "Reconstruction test", desc,
                     labels=["strat-creator-needs-attention"])
        jira.create("RHAIRFE-3050", "GPU sharing RFE",
                     "Users need cost-efficient GPU sharing across tenants.")
        jira.request("POST", "/rest/api/3/issueLink", {
            "type": {"name": "Cloners"},
            "inwardIssue": {"key": "RHAIRFE-3050"},
            "outwardIssue": {"key": "RHAISTRAT-2050"},
        })

        local_dir = tmp_path / "local"
        result = _run(jira, "RHAISTRAT-2050", local_dir)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        strat_path = local_dir / "strat-tasks" / "RHAISTRAT-2050.md"
        content = strat_path.read_text()
        assert "cost-efficient GPU sharing across tenants" in content
        assert RFE_REFERENCE_MARKER not in content
        assert BUSINESS_NEED_HEADING in content
        assert "Use MIG profiles" in content

    def test_preserves_full_business_need_when_no_reference(self, jira, tmp_path):
        """When Jira description has full RFE content (no reference marker),
        pull preserves it unchanged."""
        _setup_strat_with_rfe(jira, "RHAISTRAT-2051", "RHAIRFE-3051",
                              labels=["strat-creator-rubric-pass"])

        local_dir = tmp_path / "local"
        result = _run(jira, "RHAISTRAT-2051", local_dir)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        strat_path = local_dir / "strat-tasks" / "RHAISTRAT-2051.md"
        content = strat_path.read_text()
        assert "Users need GPU sharing" in content
        assert RFE_REFERENCE_MARKER not in content

    def test_round_trip_with_rfe_reference(self, jira, tmp_path):
        """Push with source_rfe (strips RFE), pull back (reconstructs).
        Verifies full cycle preserves Business Need."""
        jira.create("RHAISTRAT-2052", "Round trip ref",
                     "## Business Need\n\nOriginal RFE about model serving.",
                     labels=["strat-creator-rubric-pass"])
        jira.create("RHAIRFE-3052", "Model serving RFE",
                     "Users need multi-model serving with GPU sharing.")
        jira.request("POST", "/rest/api/3/issueLink", {
            "type": {"name": "Cloners"},
            "inwardIssue": {"key": "RHAIRFE-3052"},
            "outwardIssue": {"key": "RHAISTRAT-2052"},
        })

        push_script = os.path.join(PROJECT_ROOT, "scripts", "push_strategy.py")
        push_dir = tmp_path / "push-workspace" / "artifacts"
        (push_dir / "strat-tasks").mkdir(parents=True)
        (push_dir / "strat-originals").mkdir(parents=True)

        push_file = push_dir / "strat-tasks" / "RHAISTRAT-2052.md"
        push_file.write_text(
            "---\n"
            "source_rfe: RHAIRFE-3052\n"
            "---\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "### Technical Approach\n\n"
            "Deploy model serving with GPU time-slicing.\n"
        )

        push_env = _env(jira)
        push_result = subprocess.run(
            [sys.executable, push_script, "RHAISTRAT-2052", str(push_file)],
            env=push_env, capture_output=True, text=True, cwd=PROJECT_ROOT)
        assert push_result.returncode == 0, f"push stderr: {push_result.stderr}"

        local_dir = tmp_path / "local"
        pull_result = _run(jira, "RHAISTRAT-2052", local_dir)
        assert pull_result.returncode == 0, f"pull stderr: {pull_result.stderr}"

        pulled_path = local_dir / "strat-tasks" / "RHAISTRAT-2052.md"
        content = pulled_path.read_text()
        assert "multi-model serving with GPU sharing" in content
        assert BUSINESS_NEED_HEADING in content
        assert RFE_REFERENCE_MARKER not in content
        assert "GPU time-slicing" in content

    def test_pull_with_reference_but_no_cloners_link(self, jira, tmp_path):
        """When Jira description has a reference link but no Cloners link,
        pull succeeds with a warning and keeps the reference marker."""
        rfe_ref = build_rfe_reference("RHAIRFE-3060", jira.url)
        desc = (
            f"{rfe_ref}\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "### Technical Approach\n\n"
            "Use vLLM.\n"
        )
        jira.create("RHAISTRAT-2060", "No cloners link", desc,
                     labels=["strat-creator-needs-attention"])

        local_dir = tmp_path / "local"
        result = _run(jira, "RHAISTRAT-2060", local_dir)
        assert result.returncode == 0, f"stderr: {result.stderr}"
        assert "WARNING" in result.stderr
        assert "no linked RHAIRFE" in result.stderr

        strat_path = local_dir / "strat-tasks" / "RHAISTRAT-2060.md"
        content = strat_path.read_text()
        assert RFE_REFERENCE_MARKER in content
        assert "Use vLLM" in content

    def test_round_trip_preserves_staff_input(self, jira, tmp_path):
        """Push with source_rfe + Staff Input, pull back — both Business Need
        reconstructed AND Staff Input preserved."""
        jira.create("RHAISTRAT-2053", "Staff input round trip",
                     "## Business Need\n\nOriginal RFE about pipelines.",
                     labels=["strat-creator-rubric-pass"])
        jira.create("RHAIRFE-3053", "Pipeline RFE",
                     "Users need automated ML pipelines.")
        jira.request("POST", "/rest/api/3/issueLink", {
            "type": {"name": "Cloners"},
            "inwardIssue": {"key": "RHAIRFE-3053"},
            "outwardIssue": {"key": "RHAISTRAT-2053"},
        })

        push_script = os.path.join(PROJECT_ROOT, "scripts", "push_strategy.py")
        push_dir = tmp_path / "push-workspace" / "artifacts"
        (push_dir / "strat-tasks").mkdir(parents=True)
        (push_dir / "strat-originals").mkdir(parents=True)

        push_file = push_dir / "strat-tasks" / "RHAISTRAT-2053.md"
        push_file.write_text(
            "---\n"
            "source_rfe: RHAIRFE-3053\n"
            "---\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "### Technical Approach\n\n"
            "Deploy Kubeflow Pipelines v2.\n\n"
            "## Staff Engineer / SME Input\n\n"
            "Use Argo Workflows, not Tekton.\n"
        )

        push_env = _env(jira)
        push_result = subprocess.run(
            [sys.executable, push_script, "RHAISTRAT-2053", str(push_file)],
            env=push_env, capture_output=True, text=True, cwd=PROJECT_ROOT)
        assert push_result.returncode == 0, f"push stderr: {push_result.stderr}"

        local_dir = tmp_path / "local"
        pull_result = _run(jira, "RHAISTRAT-2053", local_dir)
        assert pull_result.returncode == 0, f"pull stderr: {pull_result.stderr}"

        pulled_path = local_dir / "strat-tasks" / "RHAISTRAT-2053.md"
        content = pulled_path.read_text()
        assert "automated ML pipelines" in content
        assert BUSINESS_NEED_HEADING in content
        assert RFE_REFERENCE_MARKER not in content
        assert "Kubeflow Pipelines v2" in content
        assert "Argo Workflows, not Tekton" in content

    def test_double_cycle_push_pull(self, jira, tmp_path):
        """Two push→pull cycles: verify content survives both rounds."""
        jira.create("RHAISTRAT-2054", "Double cycle test",
                     "## Business Need\n\nRFE about model monitoring.",
                     labels=["strat-creator-needs-attention"])
        jira.create("RHAIRFE-3054", "Monitoring RFE",
                     "Users need real-time model drift detection.")
        jira.request("POST", "/rest/api/3/issueLink", {
            "type": {"name": "Cloners"},
            "inwardIssue": {"key": "RHAIRFE-3054"},
            "outwardIssue": {"key": "RHAISTRAT-2054"},
        })

        push_script = os.path.join(PROJECT_ROOT, "scripts", "push_strategy.py")
        push_dir = tmp_path / "push-workspace" / "artifacts"
        (push_dir / "strat-tasks").mkdir(parents=True)
        (push_dir / "strat-originals").mkdir(parents=True)

        # --- Cycle 1: push then pull ---
        push_file = push_dir / "strat-tasks" / "RHAISTRAT-2054.md"
        push_file.write_text(
            "---\n"
            "source_rfe: RHAIRFE-3054\n"
            "---\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "### Technical Approach\n\n"
            "First version strategy.\n"
        )
        push_env = _env(jira)
        r1 = subprocess.run(
            [sys.executable, push_script, "RHAISTRAT-2054", str(push_file)],
            env=push_env, capture_output=True, text=True, cwd=PROJECT_ROOT)
        assert r1.returncode == 0, f"push1 stderr: {r1.stderr}"

        local_dir1 = tmp_path / "local1"
        pull1 = _run(jira, "RHAISTRAT-2054", local_dir1)
        assert pull1.returncode == 0, f"pull1 stderr: {pull1.stderr}"

        content1 = (local_dir1 / "strat-tasks" / "RHAISTRAT-2054.md").read_text()
        assert "real-time model drift detection" in content1
        assert RFE_REFERENCE_MARKER not in content1

        # --- Cycle 2: push updated strategy, pull again ---
        push_file.write_text(
            "---\n"
            "source_rfe: RHAIRFE-3054\n"
            "---\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "### Technical Approach\n\n"
            "Second version strategy with drift alerting.\n"
        )
        r2 = subprocess.run(
            [sys.executable, push_script, "RHAISTRAT-2054", str(push_file)],
            env=push_env, capture_output=True, text=True, cwd=PROJECT_ROOT)
        assert r2.returncode == 0, f"push2 stderr: {r2.stderr}"

        local_dir2 = tmp_path / "local2"
        pull2 = _run(jira, "RHAISTRAT-2054", local_dir2)
        assert pull2.returncode == 0, f"pull2 stderr: {pull2.stderr}"

        content2 = (local_dir2 / "strat-tasks" / "RHAISTRAT-2054.md").read_text()
        assert "real-time model drift detection" in content2
        assert BUSINESS_NEED_HEADING in content2
        assert RFE_REFERENCE_MARKER not in content2
        assert "drift alerting" in content2
        assert "First version" not in content2

    def test_pull_with_attachment_and_reference(self, jira, tmp_path):
        """Strategy stored as attachment + stub has reference marker.
        Pull should merge attachment AND reconstruct Business Need."""
        rfe_ref = build_rfe_reference("RHAIRFE-3061", jira.url)
        stub_desc = (
            f"{rfe_ref}\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "> **Note:** The full strategy exceeds Jira's description size "
            "limit and is stored as an attachment: "
            "`RHAISTRAT-2061-strategy.md`.\n\n"
            "### TL;DR\n\n"
            "Enable model serving with GPU sharing.\n"
        )
        jira.create("RHAISTRAT-2061", "Attachment + ref test", stub_desc,
                     labels=["strat-creator-rubric-pass"])
        jira.create("RHAIRFE-3061", "Model serving RFE",
                     "Users need multi-model serving with autoscaling.")
        jira.request("POST", "/rest/api/3/issueLink", {
            "type": {"name": "Cloners"},
            "inwardIssue": {"key": "RHAIRFE-3061"},
            "outwardIssue": {"key": "RHAISTRAT-2061"},
        })

        full_strategy = (
            f"{STRATEGY_HEADING}\n\n"
            "### TL;DR\n\n"
            "Enable model serving with GPU sharing.\n\n"
            "### Technical Approach\n\n"
            "Deploy vLLM with NVIDIA MPS.\n"
        )
        _upload_strategy_attachment(jira, "RHAISTRAT-2061", full_strategy)

        local_dir = tmp_path / "local"
        result = _run(jira, "RHAISTRAT-2061", local_dir)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        strat_path = local_dir / "strat-tasks" / "RHAISTRAT-2061.md"
        content = strat_path.read_text()
        assert "multi-model serving with autoscaling" in content
        assert BUSINESS_NEED_HEADING in content
        assert RFE_REFERENCE_MARKER not in content
        assert "Deploy vLLM with NVIDIA MPS" in content
        assert "attachment" in result.stdout.lower()
