import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))

from push_strategy import (
    extract_strategy_section,
    extract_staff_input_section,
    extract_tldr_section,
    extract_source_rfe,
    _build_description_stub,
    _find_strategy_attachment,
    _find_staff_input_attachment,
    STRATEGY_HEADING,
    STAFF_INPUT_HEADING,
    ATTACHMENT_NOTICE,
    ATTACHMENT_NOTICE_NO_TLDR,
    STRATEGY_ATTACHMENT_TEMPLATE,
    STAFF_INPUT_ATTACHMENT_TEMPLATE,
    STAFF_INPUT_ATTACHMENT_NOTICE,
)
from jira_utils import (
    build_rfe_reference,
    reconstruct_business_need,
    reconstruct_business_need_file,
    RFE_REFERENCE_MARKER,
    BUSINESS_NEED_HEADING,
)


class TestExtractStrategySection:

    def test_extracts_strategy_section(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "This is the strategy content.\n\n"
            "### Sub-section\n\n"
            "More details here.\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert "## Strategy (AI Generated by Agentic SDLC Pipeline)" in result
        assert "This is the strategy content." in result
        assert "More details here." in result

    def test_returns_none_when_no_strategy_section(self):
        content = (
            "## Business Need\n\n"
            "We need this feature.\n\n"
            "## Scope\n\n"
            "It is small.\n"
        )
        result = extract_strategy_section(content)
        assert result is None

    def test_stops_at_next_h2_heading(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Strategy content.\n\n"
            "## Staff Engineer / SME Input\n\n"
            "Engineer notes.\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert "Strategy content." in result
        assert "Staff Engineer / SME Input" not in result
        assert "Engineer notes." not in result

    def test_includes_h3_subsections(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Overview.\n\n"
            "### Implementation Details\n\n"
            "Details here.\n\n"
            "### Testing Plan\n\n"
            "Test plan here.\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert "### Implementation Details" in result
        assert "### Testing Plan" in result
        assert "Details here." in result
        assert "Test plan here." in result

    def test_extraction_in_full_document(self):
        content = (
            "## Business Need\n\n"
            "Users need GPU sharing for cost efficiency.\n\n"
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Enable time-sliced GPU sharing via MIG.\n\n"
            "### Architecture\n\n"
            "Use the NVIDIA device plugin.\n\n"
            "## Staff Engineer / SME Input\n\n"
            "*Add technical corrections here.*\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert "Enable time-sliced GPU sharing via MIG." in result
        assert "Use the NVIDIA device plugin." in result
        assert "Business Need" not in result
        assert "Users need GPU sharing" not in result
        assert "Staff Engineer / SME Input" not in result

    def test_strategy_at_end_of_file(self):
        content = (
            "## Business Need\n\n"
            "Context.\n\n"
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Final section content.\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert "Final section content." in result

    def test_strategy_with_frontmatter_stripped(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Content after frontmatter was stripped.\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert "Content after frontmatter was stripped." in result

    def test_wrong_heading_not_matched(self):
        content = (
            "## Strategy\n\n"
            "This heading is missing the parenthetical.\n"
        )
        result = extract_strategy_section(content)
        assert result is None

    def test_result_is_stripped(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Content.\n\n\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert not result.endswith("\n\n")


class TestExtractStaffInputSection:

    def test_extracts_staff_input(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Strategy content.\n\n"
            "## Staff Engineer / SME Input\n\n"
            "Effort estimate is too low.\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert "## Staff Engineer / SME Input" in result
        assert "Effort estimate is too low." in result
        assert "Strategy content." not in result

    def test_returns_none_when_no_staff_input(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Strategy content.\n"
        )
        result = extract_staff_input_section(content)
        assert result is None

    def test_extracts_template_only(self):
        content = (
            "## Staff Engineer / SME Input\n\n"
            "*Add technical corrections here.*\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert "## Staff Engineer / SME Input" in result

    def test_staff_input_at_end_of_file(self):
        content = (
            "## Business Need\n\nContext.\n\n"
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Strategy.\n\n"
            "## Staff Engineer / SME Input\n\n"
            "Add dependency on RHAISTRAT-1200.\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert "Add dependency on RHAISTRAT-1200." in result
        assert "Business Need" not in result
        assert "Strategy." not in result

    def test_stops_at_next_h2(self):
        content = (
            "## Staff Engineer / SME Input\n\n"
            "Notes here.\n\n"
            "## Another Section\n\n"
            "Other content.\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert "Notes here." in result
        assert "Another Section" not in result
        assert "Other content." not in result

    def test_includes_h3_subsections(self):
        content = (
            "## Staff Engineer / SME Input\n\n"
            "Overview.\n\n"
            "### Corrections\n\n"
            "Fix the estimate.\n\n"
            "### Links\n\n"
            "See RHAISTRAT-1200.\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert "### Corrections" in result
        assert "### Links" in result

    def test_result_is_stripped(self):
        content = (
            "## Staff Engineer / SME Input\n\n"
            "Content.\n\n\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert not result.endswith("\n\n")

    def test_extracts_legacy_heading(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Strategy content.\n\n"
            "## Staff Engineer Input\n\n"
            "Legacy notes from Jira.\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert "## Staff Engineer Input" in result
        assert "Legacy notes from Jira." in result

    def test_legacy_heading_stops_at_next_h2(self):
        content = (
            "## Staff Engineer Input\n\n"
            "Notes here.\n\n"
            "## Another Section\n\n"
            "Other content.\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert "Notes here." in result
        assert "Another Section" not in result


class TestExtractTldrSection:

    def test_extracts_tldr_with_components(self):
        strategy = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "### TL;DR\n\n"
            "Enable GPU sharing via MIG profiles.\n\n"
            "**Components**: nvidia-device-plugin, dashboard\n\n"
            "### Technical Approach\n\n"
            "Use the NVIDIA device plugin.\n"
        )
        result = extract_tldr_section(strategy)
        assert result is not None
        assert "### TL;DR" in result
        assert "GPU sharing via MIG profiles" in result
        assert "**Components**" in result
        assert "Technical Approach" not in result

    def test_returns_none_when_no_tldr(self):
        strategy = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "### Technical Approach\n\n"
            "Details here.\n"
        )
        result = extract_tldr_section(strategy)
        assert result is None

    def test_tldr_at_end_of_strategy(self):
        strategy = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "### Technical Approach\n\nDetails.\n\n"
            "### TL;DR\n\n"
            "Final summary.\n"
        )
        result = extract_tldr_section(strategy)
        assert result is not None
        assert "Final summary." in result

    def test_tldr_stops_at_next_h3(self):
        strategy = (
            "### TL;DR\n\n"
            "Summary text.\n\n"
            "### Risks\n\n"
            "Risk details.\n"
        )
        result = extract_tldr_section(strategy)
        assert result is not None
        assert "Summary text." in result
        assert "Risks" not in result
        assert "Risk details." not in result

    def test_result_is_stripped(self):
        strategy = (
            "### TL;DR\n\n"
            "Summary.\n\n\n"
        )
        result = extract_tldr_section(strategy)
        assert result is not None
        assert not result.endswith("\n\n")


class TestBuildDescriptionStub:

    def test_stub_with_tldr(self):
        existing_md = (
            "## Business Need\n\n"
            "Users need GPU sharing.\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "### TL;DR\n\n"
            "Enable GPU sharing.\n\n"
            "### Technical Approach\n\n"
            "Use MIG.\n"
        )
        strategy_section = (
            f"{STRATEGY_HEADING}\n\n"
            "### TL;DR\n\n"
            "Enable GPU sharing.\n\n"
            "### Technical Approach\n\n"
            "Use MIG.\n"
        )
        result = _build_description_stub(
            existing_md, strategy_section, None, "RHAISTRAT-1000-strategy.md")
        assert "Business Need" in result
        assert "Users need GPU sharing" in result
        assert STRATEGY_HEADING in result
        assert "### TL;DR" in result
        assert "Enable GPU sharing" in result
        assert "### Technical Approach" not in result
        assert "RHAISTRAT-1000-strategy.md" in result

    def test_stub_without_tldr(self):
        existing_md = "## Business Need\n\nContext.\n"
        strategy_section = (
            f"{STRATEGY_HEADING}\n\n"
            "### Technical Approach\n\n"
            "Details.\n"
        )
        result = _build_description_stub(
            existing_md, strategy_section, None, "RHAISTRAT-1000-strategy.md")
        assert STRATEGY_HEADING in result
        assert "### TL;DR" not in result
        assert "RHAISTRAT-1000-strategy.md" in result

    def test_stub_preserves_business_need(self):
        existing_md = (
            "## Business Need\n\n"
            "Critical business context that must be preserved.\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "Old strategy.\n"
        )
        strategy_section = f"{STRATEGY_HEADING}\n\nNew strategy.\n"
        result = _build_description_stub(
            existing_md, strategy_section, None, "RHAISTRAT-1000-strategy.md")
        assert "Critical business context that must be preserved" in result

    def test_stub_includes_staff_input_attachment_notice(self):
        existing_md = "## Business Need\n\nContext.\n"
        strategy_section = f"{STRATEGY_HEADING}\n\nStrategy.\n"
        result = _build_description_stub(
            existing_md, strategy_section, "RHAISTRAT-1000-strategy.md",
            staff_input_attachment_filename="RHAISTRAT-1000-staff-input.md")
        assert STAFF_INPUT_HEADING in result
        assert "RHAISTRAT-1000-staff-input.md" in result
        assert "stored as attachment" in result

    def test_stub_adds_staff_input_template_when_missing(self):
        existing_md = "## Business Need\n\nContext.\n"
        strategy_section = f"{STRATEGY_HEADING}\n\nStrategy.\n"
        result = _build_description_stub(
            existing_md, strategy_section, None, "RHAISTRAT-1000-strategy.md")
        assert STAFF_INPUT_HEADING in result

    def test_stub_does_not_duplicate_staff_input(self):
        existing_md = (
            "## Business Need\n\nContext.\n\n"
            f"{STAFF_INPUT_HEADING}\n\nExisting notes.\n"
        )
        strategy_section = f"{STRATEGY_HEADING}\n\nStrategy.\n"
        result = _build_description_stub(
            existing_md, strategy_section, "RHAISTRAT-1000-strategy.md",
            staff_input_attachment_filename="RHAISTRAT-1000-staff-input.md")
        count = result.count(STAFF_INPUT_HEADING)
        assert count == 1
        assert "Existing notes" not in result
        assert "RHAISTRAT-1000-staff-input.md" in result


class TestFindStrategyAttachment:

    def test_finds_matching_attachment(self):
        attachments = [
            {"filename": "RHAISTRAT-1000-review.md", "id": "100"},
            {"filename": "RHAISTRAT-1000-strategy.md", "id": "200"},
        ]
        result = _find_strategy_attachment(attachments, "RHAISTRAT-1000")
        assert result is not None
        assert result["id"] == "200"

    def test_returns_none_when_no_match(self):
        attachments = [
            {"filename": "RHAISTRAT-1000-review.md", "id": "100"},
        ]
        result = _find_strategy_attachment(attachments, "RHAISTRAT-1000")
        assert result is None

    def test_returns_none_for_empty_list(self):
        result = _find_strategy_attachment([], "RHAISTRAT-1000")
        assert result is None

    def test_matches_correct_issue_key(self):
        attachments = [
            {"filename": "RHAISTRAT-2000-strategy.md", "id": "300"},
        ]
        result = _find_strategy_attachment(attachments, "RHAISTRAT-1000")
        assert result is None


class TestFindStaffInputAttachment:

    def test_finds_matching_attachment(self):
        attachments = [
            {"filename": "RHAISTRAT-1000-strategy.md", "id": "100"},
            {"filename": "RHAISTRAT-1000-staff-input.md", "id": "200"},
        ]
        result = _find_staff_input_attachment(attachments, "RHAISTRAT-1000")
        assert result is not None
        assert result["id"] == "200"

    def test_returns_none_when_no_match(self):
        attachments = [
            {"filename": "RHAISTRAT-1000-strategy.md", "id": "100"},
        ]
        result = _find_staff_input_attachment(attachments, "RHAISTRAT-1000")
        assert result is None

    def test_returns_none_for_empty_list(self):
        result = _find_staff_input_attachment([], "RHAISTRAT-1000")
        assert result is None

    def test_matches_correct_issue_key(self):
        attachments = [
            {"filename": "RHAISTRAT-2000-staff-input.md", "id": "300"},
        ]
        result = _find_staff_input_attachment(attachments, "RHAISTRAT-1000")
        assert result is None


class TestExtractSourceRfe:

    def test_extracts_from_valid_frontmatter(self):
        content = (
            "---\n"
            "strat_id: RHAISTRAT-1000\n"
            "source_rfe: RHAIRFE-1234\n"
            "status: Refined\n"
            "---\n\n"
            "## Business Need\n\nContent.\n"
        )
        assert extract_source_rfe(content) == "RHAIRFE-1234"

    def test_returns_none_when_no_frontmatter(self):
        content = "## Business Need\n\nContent.\n"
        assert extract_source_rfe(content) is None

    def test_returns_none_when_source_rfe_missing(self):
        content = (
            "---\n"
            "strat_id: RHAISTRAT-1000\n"
            "status: Refined\n"
            "---\n\n"
            "Content.\n"
        )
        assert extract_source_rfe(content) is None

    def test_handles_different_rfe_numbers(self):
        content = (
            "---\n"
            "source_rfe: RHAIRFE-99999\n"
            "---\n\n"
            "Content.\n"
        )
        assert extract_source_rfe(content) == "RHAIRFE-99999"

    def test_rejects_placeholder_rhairfe_0(self):
        content = (
            "---\n"
            "source_rfe: RHAIRFE-0\n"
            "---\n\n"
            "Content.\n"
        )
        assert extract_source_rfe(content) is None


class TestBuildRfeReference:

    def test_correct_format(self):
        result = build_rfe_reference("RHAIRFE-1234", "https://jira.example.com")
        assert BUSINESS_NEED_HEADING in result
        assert RFE_REFERENCE_MARKER in result
        assert "[RHAIRFE-1234](https://jira.example.com/browse/RHAIRFE-1234)" in result

    def test_different_server(self):
        result = build_rfe_reference("RHAIRFE-5678", "https://redhat.atlassian.net")
        assert "https://redhat.atlassian.net/browse/RHAIRFE-5678" in result

    def test_strips_trailing_slash_from_server(self):
        result = build_rfe_reference("RHAIRFE-1", "https://jira.example.com/")
        assert "https://jira.example.com/browse/RHAIRFE-1" in result
        assert "//browse" not in result


class TestReconstructBusinessNeed:

    def test_reconstructs_when_reference_present(self):
        description = (
            f"{BUSINESS_NEED_HEADING}\n\n"
            f"> {RFE_REFERENCE_MARKER} "
            "[RHAIRFE-1234](https://jira.example.com/browse/RHAIRFE-1234)\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "Strategy content.\n"
        )
        rfe_md = "Users need GPU sharing for cost efficiency."
        result = reconstruct_business_need(description, rfe_md)
        assert "Users need GPU sharing" in result
        assert RFE_REFERENCE_MARKER not in result
        assert STRATEGY_HEADING in result
        assert "Strategy content." in result

    def test_preserves_full_content_when_no_reference(self):
        description = (
            f"{BUSINESS_NEED_HEADING}\n\n"
            "Full RFE content already here.\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "Strategy content.\n"
        )
        rfe_md = "Some RFE."
        result = reconstruct_business_need(description, rfe_md)
        assert result == description

    def test_returns_unchanged_when_no_rfe_md(self):
        description = (
            f"{BUSINESS_NEED_HEADING}\n\n"
            f"> {RFE_REFERENCE_MARKER} [RHAIRFE-1](https://x)\n\n"
            f"{STRATEGY_HEADING}\n\nStrategy.\n"
        )
        result = reconstruct_business_need(description, "")
        assert result == description

    def test_returns_unchanged_when_no_strategy_heading(self):
        description = (
            f"{BUSINESS_NEED_HEADING}\n\n"
            f"> {RFE_REFERENCE_MARKER} [RHAIRFE-1](https://x)\n"
        )
        result = reconstruct_business_need(description, "RFE content.")
        assert result == description

    def test_reconstruction_preserves_staff_input_after_strategy(self):
        """Staff Input after Strategy heading survives reconstruction."""
        description = (
            f"{BUSINESS_NEED_HEADING}\n\n"
            f"> {RFE_REFERENCE_MARKER} [RHAIRFE-1](https://x)\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "### Technical Approach\n\n"
            "Use MIG profiles.\n\n"
            f"{STAFF_INPUT_HEADING}\n\n"
            "Use Argo Workflows, not Tekton.\n"
        )
        rfe_md = "Users need GPU sharing for cost efficiency."
        result = reconstruct_business_need(description, rfe_md)
        assert "Users need GPU sharing" in result
        assert STRATEGY_HEADING in result
        assert "Use MIG profiles" in result
        assert "Use Argo Workflows, not Tekton" in result
        assert RFE_REFERENCE_MARKER not in result

    def test_returns_unchanged_when_marker_present_but_no_rfe_content(self):
        """Returns unchanged when reference marker found but rfe_md empty."""
        description = (
            f"{BUSINESS_NEED_HEADING}\n\n"
            f"> {RFE_REFERENCE_MARKER} [RHAIRFE-1](https://x)\n\n"
            f"{STRATEGY_HEADING}\n\nStrategy.\n"
        )
        result = reconstruct_business_need(description, "")
        assert result == description


class TestReconstructBusinessNeedFile:

    def _write(self, tmp_path, name, content):
        p = tmp_path / name
        p.write_text(content, encoding="utf-8")
        return str(p)

    def test_reconstructs_with_frontmatter(self, tmp_path):
        strat = self._write(tmp_path, "strat.md", (
            "---\nstrat_id: RHAISTRAT-100\nsource_rfe: RHAIRFE-50\n---\n"
            f"{BUSINESS_NEED_HEADING}\n\n"
            f"> {RFE_REFERENCE_MARKER} [RHAIRFE-50](https://x)\n\n"
            f"{STRATEGY_HEADING}\n\nStrategy content.\n"
        ))
        rfe = self._write(tmp_path, "rfe.md", "Full RFE description here.")
        assert reconstruct_business_need_file(strat, rfe) is True
        result = (tmp_path / "strat.md").read_text()
        assert "strat_id: RHAISTRAT-100" in result
        assert "Full RFE description here." in result
        assert RFE_REFERENCE_MARKER not in result
        assert "Strategy content." in result

    def test_returns_false_when_no_reference_marker(self, tmp_path):
        strat = self._write(tmp_path, "strat.md", (
            "---\nstrat_id: RHAISTRAT-100\n---\n"
            f"{BUSINESS_NEED_HEADING}\n\nAlready has full content.\n\n"
            f"{STRATEGY_HEADING}\n\nStrategy.\n"
        ))
        rfe = self._write(tmp_path, "rfe.md", "RFE content.")
        assert reconstruct_business_need_file(strat, rfe) is False

    def test_returns_false_when_rfe_path_missing(self, tmp_path, capsys):
        strat = self._write(tmp_path, "strat.md", (
            f"{BUSINESS_NEED_HEADING}\n\n"
            f"> {RFE_REFERENCE_MARKER} [RHAIRFE-1](https://x)\n\n"
            f"{STRATEGY_HEADING}\n\nStrategy.\n"
        ))
        assert reconstruct_business_need_file(strat, str(tmp_path / "missing.md")) is False
        captured = capsys.readouterr()
        assert "WARNING" in captured.err
        assert "missing.md" in captured.err

    def test_returns_false_when_rfe_file_empty(self, tmp_path):
        strat = self._write(tmp_path, "strat.md", (
            f"{BUSINESS_NEED_HEADING}\n\n"
            f"> {RFE_REFERENCE_MARKER} [RHAIRFE-1](https://x)\n\n"
            f"{STRATEGY_HEADING}\n\nStrategy.\n"
        ))
        rfe = self._write(tmp_path, "rfe.md", "   \n  ")
        assert reconstruct_business_need_file(strat, rfe) is False

    def test_works_without_frontmatter(self, tmp_path):
        strat = self._write(tmp_path, "strat.md", (
            f"{BUSINESS_NEED_HEADING}\n\n"
            f"> {RFE_REFERENCE_MARKER} [RHAIRFE-1](https://x)\n\n"
            f"{STRATEGY_HEADING}\n\nStrategy content.\n"
        ))
        rfe = self._write(tmp_path, "rfe.md", "Full RFE text.")
        assert reconstruct_business_need_file(strat, rfe) is True
        result = (tmp_path / "strat.md").read_text()
        assert "Full RFE text." in result
        assert RFE_REFERENCE_MARKER not in result

    def test_idempotent_on_second_call(self, tmp_path):
        strat = self._write(tmp_path, "strat.md", (
            "---\nsource_rfe: RHAIRFE-1\n---\n"
            f"{BUSINESS_NEED_HEADING}\n\n"
            f"> {RFE_REFERENCE_MARKER} [RHAIRFE-1](https://x)\n\n"
            f"{STRATEGY_HEADING}\n\nStrategy.\n"
        ))
        rfe = self._write(tmp_path, "rfe.md", "Full RFE.")
        assert reconstruct_business_need_file(strat, rfe) is True
        first_result = (tmp_path / "strat.md").read_text()
        assert reconstruct_business_need_file(strat, rfe) is False
        second_result = (tmp_path / "strat.md").read_text()
        assert first_result == second_result

    def test_frontmatter_without_trailing_newline(self, tmp_path):
        """Handles frontmatter where closing --- has no trailing newline."""
        strat = self._write(tmp_path, "strat.md", (
            "---\nstrat_id: X\n---"
            f"{BUSINESS_NEED_HEADING}\n\n"
            f"> {RFE_REFERENCE_MARKER} [RHAIRFE-1](https://x)\n\n"
            f"{STRATEGY_HEADING}\n\nStrategy.\n"
        ))
        rfe = self._write(tmp_path, "rfe.md", "Full RFE.")
        assert reconstruct_business_need_file(strat, rfe) is True
        result = (tmp_path / "strat.md").read_text()
        assert "strat_id: X" in result
        assert "Full RFE." in result
        assert "---\n## Business Need" in result
