"""Integration tests for push_strategy.py against jira-emulator."""
import os
import subprocess
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))

from jira_utils import adf_to_markdown, RFE_REFERENCE_MARKER

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SCRIPT = os.path.join(PROJECT_ROOT, "scripts", "push_strategy.py")

STRATEGY_HEADING = "## Strategy (AI Generated by Agentic SDLC Pipeline)"
STAFF_INPUT_HEADING = "## Staff Engineer / SME Input"


def _env(jira):
    return {
        **os.environ,
        "JIRA_SERVER": jira.url,
        "JIRA_USER": "admin",
        "JIRA_TOKEN": "admin",
    }


def _run(jira, issue_key, local_file):
    return subprocess.run(
        [sys.executable, SCRIPT, issue_key, str(local_file)],
        env=_env(jira),
        capture_output=True,
        text=True,
        cwd=PROJECT_ROOT,
    )


def _get_description_markdown(jira, key):
    issue = jira.get(key)
    desc = issue.get("fields", {}).get("description")
    if desc is None:
        return ""
    return adf_to_markdown(desc).strip()


class TestPushNewStrategy:

    def test_pushes_strategy_section_to_empty_description(self, jira, art_dir):
        jira.create("RHAISTRAT-1000", "Test strategy push", "")

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1000.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "### Goal\n\n"
            "Enable GPU time-slicing via MIG profiles.\n\n"
            "### Implementation\n\n"
            "Use the NVIDIA device plugin.\n"
        )

        result = _run(jira, "RHAISTRAT-1000", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1000")
        assert "GPU time-slicing via MIG profiles" in md
        assert "NVIDIA device plugin" in md
        assert STAFF_INPUT_HEADING in md

    def test_preserves_business_need_content(self, jira, art_dir):
        jira.create("RHAISTRAT-1002", "Preserve business need",
                     "## Business Need\n\nUsers need cost-efficient GPU sharing.")

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1002.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "### Approach\n\n"
            "Time-sliced GPU sharing with MIG.\n"
        )

        result = _run(jira, "RHAISTRAT-1002", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1002")
        assert "Business Need" in md
        assert "cost-efficient GPU sharing" in md
        assert "Time-sliced GPU sharing with MIG" in md
        assert STAFF_INPUT_HEADING in md

    def test_creates_backup_file(self, jira, art_dir):
        jira.create("RHAISTRAT-1003", "Backup test",
                     "## Business Need\n\nOriginal content for backup.")

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1003.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "Strategy content.\n"
        )

        result = _run(jira, "RHAISTRAT-1003", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        backup_path = art_dir / "artifacts" / "strat-originals" / "RHAISTRAT-1003-pre-push.md"
        assert backup_path.exists()
        backup_content = backup_path.read_text()
        assert "Original content for backup" in backup_content

    def test_appends_staff_engineer_input_template(self, jira, art_dir):
        jira.create("RHAISTRAT-1004", "Staff input template",
                     "## Business Need\n\nContext.")

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1004.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "Strategy details.\n"
        )

        result = _run(jira, "RHAISTRAT-1004", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1004")
        assert STAFF_INPUT_HEADING in md


class TestPushReplacement:

    def test_replaces_existing_strategy_section(self, jira, art_dir):
        existing_desc = (
            "## Business Need\n\n"
            "Users need GPU sharing.\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "Old strategy content that should be replaced.\n\n"
            f"{STAFF_INPUT_HEADING}\n\n"
            "Engineer notes.\n"
        )
        jira.create("RHAISTRAT-1001", "Replace strategy", existing_desc)

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1001.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "### Updated Approach\n\n"
            "Brand new strategy content.\n"
        )

        result = _run(jira, "RHAISTRAT-1001", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1001")
        assert "Brand new strategy content" in md
        assert "Old strategy content that should be replaced" not in md

    def test_preserves_surrounding_sections(self, jira, art_dir):
        existing_desc = (
            "## Business Need\n\n"
            "Critical business context.\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "Old strategy.\n\n"
            f"{STAFF_INPUT_HEADING}\n\n"
            "Staff notes.\n"
        )
        jira.create("RHAISTRAT-1005", "Preserve surroundings", existing_desc)

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1005.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "Replacement strategy.\n"
        )

        result = _run(jira, "RHAISTRAT-1005", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1005")
        assert "Critical business context" in md
        assert "Replacement strategy" in md
        assert "Old strategy" not in md

    def test_does_not_duplicate_strategy_section(self, jira, art_dir):
        existing_desc = (
            f"{STRATEGY_HEADING}\n\n"
            "First version.\n"
        )
        jira.create("RHAISTRAT-1006", "No duplication", existing_desc)

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1006.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "Second version.\n"
        )

        result = _run(jira, "RHAISTRAT-1006", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1006")
        count = md.count("Strategy (AI Generated by Agentic SDLC Pipeline)")
        assert count == 1
        assert "Second version" in md
        assert "First version" not in md

    def test_does_not_duplicate_staff_input(self, jira, art_dir):
        existing_desc = (
            "## Business Need\n\nContext.\n\n"
            f"{STRATEGY_HEADING}\n\nOld strat.\n\n"
            f"{STAFF_INPUT_HEADING}\n\nExisting engineer notes.\n"
        )
        jira.create("RHAISTRAT-1007", "No duplicate staff input", existing_desc)

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1007.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "New strat.\n"
        )

        result = _run(jira, "RHAISTRAT-1007", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1007")
        count = md.count("Staff Engineer / SME Input")
        assert count == 1


STAFF_INPUT_HEADING_LEGACY = "## Staff Engineer Input"


class TestPushLegacyHeading:

    def test_replaces_legacy_staff_input_without_duplication(self, jira, art_dir):
        existing_desc = (
            "## Business Need\n\nContext.\n\n"
            f"{STRATEGY_HEADING}\n\nOld strat.\n\n"
            f"{STAFF_INPUT_HEADING_LEGACY}\n\nLegacy engineer notes.\n"
        )
        jira.create("RHAISTRAT-1050", "Legacy heading replace", existing_desc)

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1050.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "New strat.\n\n"
            f"{STAFF_INPUT_HEADING}\n\nUpdated SME notes.\n"
        )

        result = _run(jira, "RHAISTRAT-1050", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1050")
        assert "Updated SME notes" in md
        assert "Legacy engineer notes" not in md
        count_new = md.count("Staff Engineer / SME Input")
        count_legacy = md.count("Staff Engineer Input")
        assert count_new + count_legacy == 1

    def test_preserves_legacy_staff_input_when_no_local_input(self, jira, art_dir):
        existing_desc = (
            "## Business Need\n\nContext.\n\n"
            f"{STRATEGY_HEADING}\n\nOld strat.\n\n"
            f"{STAFF_INPUT_HEADING_LEGACY}\n\nExisting legacy notes.\n"
        )
        jira.create("RHAISTRAT-1051", "Legacy heading preserve", existing_desc)

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1051.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "New strat.\n"
        )

        result = _run(jira, "RHAISTRAT-1051", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1051")
        assert "New strat" in md
        assert "Existing legacy notes" in md
        count_new = md.count("Staff Engineer / SME Input")
        count_legacy = md.count("Staff Engineer Input")
        assert count_new + count_legacy == 1

    def test_legacy_heading_no_duplicate_with_template(self, jira, art_dir):
        existing_desc = (
            "## Business Need\n\nContext.\n\n"
            f"{STAFF_INPUT_HEADING_LEGACY}\n\nLegacy notes.\n"
        )
        jira.create("RHAISTRAT-1052", "Legacy no dup template", existing_desc)

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1052.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "Strategy content.\n"
        )

        result = _run(jira, "RHAISTRAT-1052", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1052")
        count_new = md.count("Staff Engineer / SME Input")
        count_legacy = md.count("Staff Engineer Input")
        assert count_new + count_legacy == 1


class TestPushErrors:

    def test_missing_strategy_section_exits_1(self, jira, art_dir):
        jira.create("RHAISTRAT-1010", "No strategy", "Business need only.")

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1010.md"
        local_file.write_text(
            "## Business Need\n\n"
            "This file has no strategy section.\n"
        )

        result = _run(jira, "RHAISTRAT-1010", local_file)
        assert result.returncode == 1
        assert "no strategy section" in result.stderr.lower()

    def test_missing_env_vars_exits_2(self, jira, art_dir):
        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1011.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\nContent.\n"
        )

        env = {k: v for k, v in os.environ.items()
               if k not in ("JIRA_SERVER", "JIRA_USER", "JIRA_TOKEN")}
        result = subprocess.run(
            [sys.executable, SCRIPT, "RHAISTRAT-1011", str(local_file)],
            env=env,
            capture_output=True,
            text=True,
            cwd=PROJECT_ROOT,
        )
        assert result.returncode == 2

    def test_missing_local_file_exits_nonzero(self, jira, art_dir):
        nonexistent = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1012.md"

        result = _run(jira, "RHAISTRAT-1012", nonexistent)
        assert result.returncode != 0


class TestPushBackupBehavior:

    def test_backup_not_overwritten_on_second_push(self, jira, art_dir):
        jira.create("RHAISTRAT-1020", "Backup idempotency",
                     "## Business Need\n\nOriginal content.")

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1020.md"

        local_file.write_text(
            f"{STRATEGY_HEADING}\n\nFirst push.\n"
        )
        result1 = _run(jira, "RHAISTRAT-1020", local_file)
        assert result1.returncode == 0, f"stderr: {result1.stderr}"

        backup_path = art_dir / "artifacts" / "strat-originals" / "RHAISTRAT-1020-pre-push.md"
        assert backup_path.exists()
        first_backup = backup_path.read_text()
        assert "Original content" in first_backup

        local_file.write_text(
            f"{STRATEGY_HEADING}\n\nSecond push.\n"
        )
        result2 = _run(jira, "RHAISTRAT-1020", local_file)
        assert result2.returncode == 0, f"stderr: {result2.stderr}"

        second_backup = backup_path.read_text()
        assert second_backup == first_backup

    def test_no_backup_when_description_empty(self, jira, art_dir):
        jira.create("RHAISTRAT-1021", "Empty desc", "")

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1021.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\nContent.\n"
        )

        result = _run(jira, "RHAISTRAT-1021", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        backup_path = art_dir / "artifacts" / "strat-originals" / "RHAISTRAT-1021-pre-push.md"
        assert not backup_path.exists()


class TestPushWithFrontmatter:

    def test_frontmatter_is_stripped_before_push(self, jira, art_dir):
        jira.create("RHAISTRAT-1030", "Frontmatter stripping", "")

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1030.md"
        local_file.write_text(
            "---\n"
            "status: refined\n"
            "source_rfe: RHAIRFE-1030\n"
            "---\n\n"
            "# RHAISTRAT-1030: Test Title\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "Strategy content after frontmatter.\n"
        )

        result = _run(jira, "RHAISTRAT-1030", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1030")
        assert "status: refined" not in md
        assert "source_rfe:" not in md
        assert "RHAISTRAT-1030: Test Title" not in md
        assert "Strategy content after frontmatter" in md


class TestPushRfeReference:

    def test_replaces_rfe_content_with_reference(self, jira, art_dir):
        """When source_rfe is in frontmatter, RFE content in Jira is replaced
        with a link to the source RHAIRFE."""
        jira.create("RHAISTRAT-1060", "RFE reference test",
                     "## Business Need\n\nFull RFE content that should be replaced.")

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1060.md"
        local_file.write_text(
            "---\n"
            "source_rfe: RHAIRFE-1060\n"
            "---\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "### Approach\n\n"
            "Strategy content.\n"
        )

        result = _run(jira, "RHAISTRAT-1060", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1060")
        assert RFE_REFERENCE_MARKER in md
        assert "RHAIRFE-1060" in md
        assert "Full RFE content that should be replaced" not in md
        assert "Strategy content." in md
        assert STAFF_INPUT_HEADING in md

    def test_preserves_rfe_content_without_frontmatter(self, jira, art_dir):
        """Without source_rfe in frontmatter, existing RFE content is preserved."""
        jira.create("RHAISTRAT-1061", "No frontmatter",
                     "## Business Need\n\nOriginal RFE content preserved.")

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1061.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "Strategy content.\n"
        )

        result = _run(jira, "RHAISTRAT-1061", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1061")
        assert "Original RFE content preserved" in md
        assert RFE_REFERENCE_MARKER not in md

    def test_reference_on_second_push(self, jira, art_dir):
        """Second push with source_rfe still produces the reference, not
        a double-nested reference."""
        jira.create("RHAISTRAT-1062", "Double push",
                     "## Business Need\n\nOriginal content.")

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1062.md"
        local_file.write_text(
            "---\n"
            "source_rfe: RHAIRFE-1062\n"
            "---\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "First push strategy.\n"
        )

        result1 = _run(jira, "RHAISTRAT-1062", local_file)
        assert result1.returncode == 0, f"stderr: {result1.stderr}"

        local_file.write_text(
            "---\n"
            "source_rfe: RHAIRFE-1062\n"
            "---\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "Second push strategy.\n"
        )

        result2 = _run(jira, "RHAISTRAT-1062", local_file)
        assert result2.returncode == 0, f"stderr: {result2.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1062")
        assert md.count(RFE_REFERENCE_MARKER) == 1
        assert "Second push strategy" in md
        assert "First push strategy" not in md


def _make_large_strategy(size_chars=35000):
    """Generate a strategy section large enough to trigger Jira's CONTENT_LIMIT_EXCEEDED."""
    lines = [
        f"{STRATEGY_HEADING}\n",
        "### TL;DR\n",
        "Enable GPU sharing via MIG profiles for cost-efficient multi-tenant workloads.\n",
        "**Components**: nvidia-device-plugin, dashboard, model-serving\n",
        "### Technical Approach\n",
    ]
    while sum(len(l) for l in lines) < size_chars:
        lines.append(
            "This is a detailed technical paragraph explaining the implementation "
            "approach for GPU time-slicing using NVIDIA MIG profiles. It covers "
            "the configuration of device plugins, resource quotas, scheduling "
            "policies, and integration with the model serving infrastructure.\n\n"
        )
    return "\n".join(lines)


class TestPushLargeStrategy:

    def test_large_strategy_pushed_inline(self, jira, art_dir):
        """Large strategies go inline when Jira accepts them."""
        jira.create("RHAISTRAT-1100", "Large strategy",
                     "## Business Need\n\nUsers need GPU sharing.")

        large_strategy = _make_large_strategy()
        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1100.md"
        local_file.write_text(large_strategy)

        result = _run(jira, "RHAISTRAT-1100", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1100")
        assert "Business Need" in md
        assert "### TL;DR" in md
        assert "GPU sharing via MIG profiles" in md
        assert "Technical Approach" in md

    def test_large_strategy_with_staff_input(self, jira, art_dir):
        jira.create("RHAISTRAT-1104", "Staff input preservation",
                     "## Business Need\n\nContext.")

        large_strategy = _make_large_strategy()
        staff_input = (
            f"{STAFF_INPUT_HEADING}\n\n"
            "Effort estimate should be L, not M.\n"
        )
        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1104.md"
        local_file.write_text(large_strategy + "\n\n" + staff_input)

        result = _run(jira, "RHAISTRAT-1104", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1104")
        assert STAFF_INPUT_HEADING in md
        assert "Effort estimate should be L" in md

    def test_staff_input_attachment_round_trip(self, jira, art_dir):
        """When Staff Input goes to an attachment (tier 2/3), pulling back
        should reconstruct the full Staff Input in the local file."""
        from jira_utils import add_attachment

        jira.create("RHAISTRAT-1105", "Staff input attachment RT",
                     "## Business Need\n\nContext.",
                     labels=["strat-creator-rubric-pass"])
        jira.create("RHAIRFE-1105", "RFE for RT", "RFE content.")
        jira.request("POST", "/rest/api/3/issueLink", {
            "type": {"name": "Cloners"},
            "inwardIssue": {"key": "RHAISTRAT-1105"},
            "outwardIssue": {"key": "RHAIRFE-1105"},
        })

        strategy_content = (
            f"{STRATEGY_HEADING}\n\n"
            "### TL;DR\n\nSummary here.\n\n"
            "### Technical Approach\n\nUse MIG profiles.\n"
        )
        staff_input_content = (
            f"{STAFF_INPUT_HEADING}\n\n"
            "Use Argo Workflows, not Tekton.\n"
        )

        # Simulate tier 2: strategy inline, staff input as attachment
        from push_strategy import (
            update_description, markdown_to_adf,
            STAFF_INPUT_ATTACHMENT_NOTICE,
            STAFF_INPUT_ATTACHMENT_TEMPLATE,
        )
        import tempfile

        si_notice = STAFF_INPUT_ATTACHMENT_NOTICE.format(
            filename="RHAISTRAT-1105-staff-input.md")
        full_desc = (
            "## Business Need\n\nContext.\n\n"
            f"{strategy_content}\n\n"
            f"{STAFF_INPUT_HEADING}\n\n{si_notice}"
        )
        update_description(jira.url, "admin", "admin", "RHAISTRAT-1105",
                           markdown_to_adf(full_desc))

        with tempfile.NamedTemporaryFile(
                mode="w", suffix=".md", delete=False, encoding="utf-8") as f:
            f.write(staff_input_content + "\n")
            tmp_path = f.name
        try:
            add_attachment(jira.url, "admin", "admin", "RHAISTRAT-1105",
                           tmp_path, filename="RHAISTRAT-1105-staff-input.md")
        finally:
            import os as _os
            _os.unlink(tmp_path)

        # Now pull
        pull_script = os.path.join(PROJECT_ROOT, "scripts", "pull_strategy.py")
        local_dir = art_dir / "local"
        pull_result = subprocess.run(
            [sys.executable, pull_script, "RHAISTRAT-1105",
             "--local-dir", str(local_dir)],
            env=_env(jira), capture_output=True, text=True, cwd=PROJECT_ROOT)
        assert pull_result.returncode == 0, f"stderr: {pull_result.stderr}"
        assert "staff input" in pull_result.stdout.lower()

        pulled_path = local_dir / "strat-tasks" / "RHAISTRAT-1105.md"
        content = pulled_path.read_text()
        assert "Use Argo Workflows, not Tekton" in content
        assert "Use MIG profiles" in content
