#!/usr/bin/env python3
"""Extract strategy pipeline data as JSON.

Scans timestamped run directories in a RHAISTRAT/ data directory and produces
JSON files that other tools can consume. Outputs two files:

  - runs.json:    per-run data (each run with its strategies, scores, verdicts)
  - summary.json: aggregated/deduped view across all runs (executive summary)

Usage:
    python3 scripts/extract-pipeline-data.py \
        --data-dir /path/to/RHAISTRAT \
        --output-dir /tmp/pipeline-data

    # Single file output (both in one JSON):
    python3 scripts/extract-pipeline-data.py \
        --data-dir /path/to/RHAISTRAT \
        --output /tmp/pipeline-data.json
"""

import argparse
import glob
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(__file__)))
from artifact_utils import read_frontmatter, compute_strat_labels, label_category


def extract_size(body):
    """Extract T-shirt size (S/M/L/XL) from the Effort Estimate section."""
    in_section = False
    for line in body.split("\n"):
        if re.match(r'^###?\s+Effort Estimate', line):
            in_section = True
            continue
        if in_section and line.strip():
            m = re.match(r'\*?\*?(XL|L|M|S)\b', line.strip())
            if m:
                return m.group(1)
            return None
    return None


def split_strategy_body(body):
    """Split strategy body into RFE content and AI-generated strategy."""
    marker = "## Strategy (AI Generated by Agentic SDLC Pipeline)"
    idx = body.find(marker)
    if idx == -1:
        return body, ""
    return body[:idx].rstrip(), body[idx:].strip()


def load_run_artifacts(run_dir):
    """Load tasks, reviews, and review comments from a single run directory."""
    tasks = {}
    reviews = {}
    review_comments = {}

    for pattern in ["STRAT-*.md", "RHAISTRAT-*.md"]:
        for path in sorted(glob.glob(os.path.join(run_dir, "strat-tasks", pattern))):
            try:
                meta, body = read_frontmatter(path)
                strat_id = meta.get("strat_id", Path(path).stem)
                tasks[strat_id] = {"meta": meta, "body": body}
            except Exception as e:
                print(f"  Warning: {path}: {e}", file=sys.stderr)

    for pattern in ["STRAT-*-review.md", "RHAISTRAT-*-review.md"]:
        for path in sorted(glob.glob(os.path.join(run_dir, "strat-reviews", pattern))):
            if path.endswith("-review-comment.md"):
                continue
            try:
                meta, body = read_frontmatter(path)
                strat_id = meta.get("strat_id", Path(path).stem.replace("-review", ""))
                reviews[strat_id] = {"meta": meta, "body": body}
            except Exception as e:
                print(f"  Warning: {path}: {e}", file=sys.stderr)

    for pattern in ["STRAT-*-review-comment.md", "RHAISTRAT-*-review-comment.md"]:
        for path in sorted(glob.glob(os.path.join(run_dir, "strat-reviews", pattern))):
            try:
                with open(path, encoding="utf-8") as f:
                    body = f.read()
                strat_id = Path(path).stem.replace("-review-comment", "")
                review_comments[strat_id] = body
            except Exception as e:
                print(f"  Warning: {path}: {e}", file=sys.stderr)

    skipped = []
    skipped_path = os.path.join(run_dir, "strat-skipped.md")
    if os.path.exists(skipped_path):
        with open(skipped_path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line.startswith("|") and not line.startswith("| RFE") and not line.startswith("|--"):
                    cols = [c.strip() for c in line.split("|")[1:-1]]
                    if len(cols) >= 4:
                        skipped.append({
                            "rfe_key": cols[0],
                            "title": cols[1],
                            "labels": cols[2],
                            "missing": cols[3],
                        })

    return tasks, reviews, review_comments, skipped


def pct(n, total):
    return round(100 * n / total) if total > 0 else 0


def is_approve(v):
    return v in ("approve", "approved")

def is_revise(v):
    return v in ("revise", "needs revision", "needs_revision")

def is_reject(v):
    return v in ("reject", "rejected", "infeasible")

def is_split(v):
    return v == "split"


def extract_strategy(strat_id, task, review, review_comment):
    """Build a JSON-friendly strategy dict (no HTML rendering)."""
    meta = task["meta"]
    body = task.get("body", "")
    rev_meta = review.get("meta", {}) if review else {}
    reviewers = rev_meta.get("reviewers", {})
    scores = rev_meta.get("scores", {})

    rfe_body, strategy_body = split_strategy_body(body)

    return {
        "strat_id": strat_id,
        "title": meta.get("title", ""),
        "source_rfe": meta.get("source_rfe", ""),
        "priority": meta.get("priority", ""),
        "status": meta.get("status", ""),
        "size": extract_size(body),
        "recommendation": rev_meta.get("recommendation", ""),
        "needs_attention": rev_meta.get("needs_attention", False),
        "scores": {
            "feasibility": scores.get("feasibility"),
            "testability": scores.get("testability"),
            "scope": scores.get("scope"),
            "architecture": scores.get("architecture"),
            "total": scores.get("total"),
        } if scores else None,
        "reviewers": {
            "feasibility": reviewers.get("feasibility", ""),
            "testability": reviewers.get("testability", ""),
            "scope": reviewers.get("scope", ""),
            "architecture": reviewers.get("architecture", ""),
        } if reviewers else None,
        "labels": compute_strat_labels(
            meta.get("status", ""),
            rev_meta.get("recommendation", ""),
            reviewers,
        ),
        "body": {
            "rfe": rfe_body,
            "strategy": strategy_body,
            "review": review.get("body", "") if review else "",
            "review_comment": review_comment or "",
        },
    }


def extract_run(run_dir):
    """Extract all data from a single run directory."""
    tasks, reviews, review_comments, skipped = load_run_artifacts(run_dir)
    if not tasks:
        return None

    strategies = []
    for strat_id in sorted(tasks.keys()):
        task = tasks[strat_id]
        review = reviews.get(strat_id)
        comment = review_comments.get(strat_id, "")
        strategies.append(extract_strategy(strat_id, task, review, comment))

    reviewed = [s for s in strategies if s["recommendation"] not in ("", None)]
    if not reviewed:
        return None

    total = len(strategies)
    total_reviewed = len(reviewed)
    approved = sum(1 for s in reviewed if is_approve(s["recommendation"]))
    revise = sum(1 for s in reviewed if is_revise(s["recommendation"]))
    reject = sum(1 for s in reviewed if is_reject(s["recommendation"]))
    split_count = sum(1 for s in reviewed if is_split(s["recommendation"]))
    needs_attention = sum(1 for s in reviewed if s.get("needs_attention", False))

    dimensions = ["feasibility", "testability", "scope", "architecture"]
    dim_stats = {}
    for dim in dimensions:
        scored_vals = [s["scores"][dim] for s in strategies
                       if s.get("scores") and s["scores"].get(dim) is not None]
        dim_total = len(scored_vals)
        dim_pass = sum(1 for v in scored_vals if v == 2)
        dim_partial = sum(1 for v in scored_vals if v == 1)
        dim_fail = sum(1 for v in scored_vals if v == 0)
        dim_sum = sum(scored_vals)
        dim_max = dim_total * 2
        dim_stats[dim] = {
            "total": dim_total,
            "pass": dim_pass,
            "partial": dim_partial,
            "fail": dim_fail,
            "rate": pct(dim_sum, dim_max),
        }

    scored = [s for s in strategies if s.get("scores") and s["scores"].get("total") is not None]
    avg_total_score = round(sum(s["scores"]["total"] for s in scored) / len(scored), 1) if scored else None

    return {
        "stats": {
            "total": total,
            "reviewed": total_reviewed,
            "approved": approved,
            "revise": revise,
            "reject": reject,
            "split": split_count,
            "needs_attention": needs_attention,
            "approval_rate": pct(approved, total_reviewed),
            "avg_total_score": avg_total_score,
            "dimensions": dim_stats,
        },
        "strategies": strategies,
        "skipped": skipped,
    }


def load_cost_backfill(data_dir):
    """Load historical cost data keyed by run_id."""
    path = os.path.join(data_dir, "cost-backfill.json")
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    return {}


def get_run_cost(run_id, pdata, cost_backfill):
    """Get cost data for a run from pipeline-data.json or backfill."""
    if pdata and "cost" in pdata:
        return pdata["cost"]

    if run_id in cost_backfill:
        return cost_backfill[run_id]

    return None


def scan_runs(data_dir, max_runs=None):
    """Discover all timestamped run directories and extract data."""
    runs = []
    current_target = None

    current_link = os.path.join(data_dir, "current")
    if os.path.islink(current_link):
        current_target = os.readlink(current_link)

    cost_backfill = load_cost_backfill(data_dir)

    for entry in sorted(os.listdir(data_dir)):
        entry_path = os.path.join(data_dir, entry)
        if not os.path.isdir(entry_path) or os.path.islink(entry_path):
            continue
        try:
            ts = datetime.strptime(entry, "%Y%m%d-%H%M%S")
        except ValueError:
            continue

        print(f"  Scanning run {entry}...", file=sys.stderr)
        run_data = extract_run(entry_path)
        if run_data is None:
            print(f"    Skipped (no artifacts)", file=sys.stderr)
            continue

        run_data["run_id"] = entry
        run_data["timestamp"] = ts.isoformat()
        run_data["is_current"] = (entry == current_target)

        pdata = None
        json_path = os.path.join(entry_path, "pipeline-data.json")
        if os.path.exists(json_path):
            with open(json_path, encoding="utf-8") as f:
                pdata = json.load(f)
            run_data["dry_run"] = pdata.get("dry_run", True)
            run_data["config"] = pdata.get("config")
        else:
            run_data["dry_run"] = True
            run_data["config"] = None

        cost = get_run_cost(entry, pdata, cost_backfill)
        if cost is not None:
            run_data["cost"] = cost

        runs.append(run_data)

    runs.sort(key=lambda r: r["run_id"])
    if max_runs and len(runs) > max_runs:
        runs = runs[-max_runs:]

    return runs


def compute_cost_stats(runs):
    """Aggregate cost data across runs."""
    costed = [r for r in runs if r.get("cost")]
    if not costed:
        return None

    totals = [r["cost"]["total_usd"] for r in costed]
    creates = [r["cost"]["create_usd"] for r in costed if "create_usd" in r["cost"]]
    refines = [r["cost"]["refine_usd"] for r in costed if "refine_usd" in r["cost"]]
    reviews = [r["cost"]["review_usd"] for r in costed if "review_usd" in r["cost"]]

    total_strategies = sum(r["stats"]["total"] for r in costed)

    return {
        "total_spend_usd": round(sum(totals), 2),
        "runs_with_cost_data": len(costed),
        "avg_per_run_usd": round(sum(totals) / len(totals), 2),
        "avg_per_strategy_usd": round(sum(totals) / total_strategies, 2) if total_strategies else None,
        "avg_create_usd": round(sum(creates) / len(creates), 2) if creates else None,
        "avg_refine_usd": round(sum(refines) / len(refines), 2) if refines else None,
        "avg_review_usd": round(sum(reviews) / len(reviews), 2) if reviews else None,
    }


def compute_summary(runs):
    """Dedup strategies across all runs, keeping the most recent version of each."""
    seen = {}
    for run in reversed(runs):
        for s in run["strategies"]:
            strat_id = s["strat_id"]
            if strat_id not in seen:
                seen[strat_id] = {
                    **s,
                    "run_id": run["run_id"],
                    "run_timestamp": run["timestamp"],
                }

    strategies = sorted(seen.values(), key=lambda s: s["strat_id"])
    total = len(strategies)
    reviewed = [s for s in strategies if s["recommendation"] not in ("", None)]
    total_reviewed = len(reviewed)
    approved = sum(1 for s in reviewed if is_approve(s["recommendation"]))
    revise = sum(1 for s in reviewed if is_revise(s["recommendation"]))
    reject = sum(1 for s in reviewed if is_reject(s["recommendation"]))
    split_count = sum(1 for s in reviewed if is_split(s["recommendation"]))
    needs_attention = sum(1 for s in reviewed if s.get("needs_attention", False))

    dimensions = ["feasibility", "testability", "scope", "architecture"]
    dim_stats = {}
    for dim in dimensions:
        scored_vals = [s["scores"][dim] for s in strategies
                       if s.get("scores") and s["scores"].get(dim) is not None]
        dim_total = len(scored_vals)
        dim_pass = sum(1 for v in scored_vals if v == 2)
        dim_partial = sum(1 for v in scored_vals if v == 1)
        dim_fail = sum(1 for v in scored_vals if v == 0)
        dim_sum = sum(scored_vals)
        dim_max = dim_total * 2
        dim_stats[dim] = {
            "total": dim_total,
            "pass": dim_pass,
            "partial": dim_partial,
            "fail": dim_fail,
            "rate": pct(dim_sum, dim_max),
        }

    scored = [s for s in strategies
              if s.get("scores") and s["scores"].get("total") is not None]
    avg_total_score = (round(sum(s["scores"]["total"] for s in scored) / len(scored), 1)
                       if scored else None)

    skipped_seen = {}
    for run in reversed(runs):
        for s in run.get("skipped", []):
            rfe_key = s.get("rfe_key", "")
            if rfe_key and rfe_key not in skipped_seen:
                skipped_seen[rfe_key] = s
    skipped = sorted(skipped_seen.values(), key=lambda s: s.get("rfe_key", ""))

    all_rfe_keys = set()
    for s in strategies:
        rfe = s.get("source_rfe", "")
        if rfe:
            all_rfe_keys.add(rfe)
    for s in skipped:
        rfe = s.get("rfe_key", "")
        if rfe:
            all_rfe_keys.add(rfe)

    cost_stats = compute_cost_stats(runs)

    result = {
        "total_strategies": total,
        "total_rfes": len(all_rfe_keys),
        "total_runs": len(runs),
        "reviewed": total_reviewed,
        "approved": approved,
        "revise": revise,
        "reject": reject,
        "split": split_count,
        "needs_attention": needs_attention,
        "approval_rate": pct(approved, total_reviewed),
        "avg_total_score": avg_total_score,
        "dimensions": dim_stats,
        "strategies": strategies,
        "skipped": skipped,
    }
    if cost_stats:
        result["cost_stats"] = cost_stats
    return result


def main():
    parser = argparse.ArgumentParser(description="Extract strategy pipeline data as JSON")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--data-dir", help="Path to RHAISTRAT/ directory (multi-run)")
    group.add_argument("--run-dir", help="Path to a single run directory (flat artifacts)")
    parser.add_argument("--output-dir", help="Directory to write runs.json and summary.json")
    parser.add_argument("--output", help="Single file output")
    parser.add_argument("--max-runs", type=int, default=None, help="Maximum runs to include (default: all)")
    parser.add_argument("--no-body", action="store_true",
                        help="Exclude strategy/review body text (metadata only)")
    parser.add_argument("--dry-run", action="store_true",
                        default=bool(os.environ.get("DRY_RUN", "").strip()),
                        help="Mark this run as a dry run (no Jira writes). "
                             "Also auto-detected from DRY_RUN env var.")
    parser.add_argument("--config", default=os.environ.get("CONFIG_FILE", ""),
                        help="Config file used for this run (recorded in output). "
                             "Also auto-detected from CONFIG_FILE env var.")
    args = parser.parse_args()

    if not args.output_dir and not args.output:
        parser.error("Either --output-dir or --output is required")

    generated_at = datetime.now().isoformat()

    if args.run_dir:
        print(f"Extracting single run from {args.run_dir}...", file=sys.stderr)
        run_data = extract_run(args.run_dir)
        if run_data is None:
            print("No artifacts found (all RFEs may have been skipped).", file=sys.stderr)
            sys.exit(0)
        run_data["run_id"] = os.path.basename(args.run_dir.rstrip("/"))
        run_data["timestamp"] = generated_at
        if args.no_body:
            for s in run_data["strategies"]:
                s.pop("body", None)
        result = {"generated_at": generated_at, "dry_run": args.dry_run,
                  "config": args.config or None, **run_data}
        out = args.output or os.path.join(args.output_dir, "pipeline-data.json")
        if args.output_dir:
            os.makedirs(args.output_dir, exist_ok=True)
        with open(out, "w") as f:
            json.dump(result, f, indent=2)
        print(f"Wrote {out}", file=sys.stderr)
        return

    print(f"Scanning {args.data_dir} for runs...", file=sys.stderr)
    runs = scan_runs(args.data_dir, max_runs=args.max_runs)
    print(f"Found {len(runs)} run(s)", file=sys.stderr)

    if not runs:
        print("No runs found.", file=sys.stderr)
        sys.exit(1)

    prod_runs = [r for r in runs if not r.get("dry_run", True)]

    summary = compute_summary(runs)
    prod_summary = compute_summary(prod_runs)

    if args.no_body:
        for run in runs:
            for s in run["strategies"]:
                s.pop("body", None)
        for s in summary["strategies"]:
            s.pop("body", None)
        for s in prod_summary["strategies"]:
            s.pop("body", None)

    if args.output_dir:
        os.makedirs(args.output_dir, exist_ok=True)

        runs_data = {"generated_at": generated_at, "runs": runs}
        runs_path = os.path.join(args.output_dir, "runs.json")
        with open(runs_path, "w") as f:
            json.dump(runs_data, f, indent=2)
        print(f"Wrote {runs_path}", file=sys.stderr)

        prod_runs_data = {"generated_at": generated_at, "runs": prod_runs}
        prod_runs_path = os.path.join(args.output_dir, "runs-production.json")
        with open(prod_runs_path, "w") as f:
            json.dump(prod_runs_data, f, indent=2)
        print(f"Wrote {prod_runs_path}", file=sys.stderr)

        summary_data = {"generated_at": generated_at, **summary}
        summary_path = os.path.join(args.output_dir, "summary.json")
        with open(summary_path, "w") as f:
            json.dump(summary_data, f, indent=2)
        print(f"Wrote {summary_path}", file=sys.stderr)

        prod_summary_data = {"generated_at": generated_at, **prod_summary}
        prod_summary_path = os.path.join(args.output_dir, "summary-production.json")
        with open(prod_summary_path, "w") as f:
            json.dump(prod_summary_data, f, indent=2)
        print(f"Wrote {prod_summary_path}", file=sys.stderr)

    if args.output:
        combined = {
            "generated_at": generated_at,
            "summary": summary,
            "runs": runs,
        }
        with open(args.output, "w") as f:
            json.dump(combined, f, indent=2)
        print(f"Wrote {args.output}", file=sys.stderr)

        base, ext = os.path.splitext(args.output)
        prod_output = f"{base}-production{ext}"
        prod_combined = {
            "generated_at": generated_at,
            "summary": prod_summary,
            "runs": prod_runs,
        }
        with open(prod_output, "w") as f:
            json.dump(prod_combined, f, indent=2)
        print(f"Wrote {prod_output}", file=sys.stderr)


if __name__ == "__main__":
    main()
