#!/usr/bin/env python3
"""Generate an HTML report from strategy pipeline artifacts.

Reads strat-tasks/, strat-reviews/, and config/test-rfes.yaml to produce
a self-contained HTML report with summary table and drill-down details.

Usage:
    python3 scripts/generate-report.py [--output artifacts/report.html]
"""

import argparse
import glob
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path

# Add scripts/ to path for frontmatter imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__)))
from artifact_utils import read_frontmatter, compute_strat_labels, label_category

def load_yaml_config(path):
    """Read test-rfes.yaml and return dict keyed by RFE ID."""
    import yaml
    with open(path) as f:
        data = yaml.safe_load(f)
    result = {}
    for rfe in data.get("test_rfes", []):
        result[rfe["id"]] = rfe
    return result


def split_strategy_body(body):
    """Split strategy body into RFE content and AI-generated strategy."""
    marker = "## Strategy (AI Generated by Agentic SDLC Pipeline)"
    idx = body.find(marker)
    if idx == -1:
        return body, ""
    return body[:idx].rstrip(), body[idx:].strip()


def extract_size(body):
    """Extract T-shirt size (S/M/L/XL) from the Effort Estimate section."""
    in_section = False
    for line in body.split("\n"):
        if re.match(r'^###?\s+Effort Estimate', line):
            in_section = True
            continue
        if in_section and line.strip():
            m = re.match(r'\*?\*?(XL|L|M|S)\b', line.strip())
            if m:
                return m.group(1)
            return "—"
    return "—"


def load_artifacts(artifacts_dir):
    """Load all strategy tasks, reviews, and review comments."""
    tasks = {}
    reviews = {}
    review_comments = {}

    for pattern in ["STRAT-*.md", "RHAISTRAT-*.md"]:
        for path in sorted(glob.glob(os.path.join(artifacts_dir, "strat-tasks", pattern))):
            try:
                meta, body = read_frontmatter(path)
                strat_id = meta.get("strat_id", Path(path).stem)
                tasks[strat_id] = {"meta": meta, "body": body, "path": path}
            except Exception as e:
                print(f"Warning: failed to read {path}: {e}", file=sys.stderr)

    for pattern in ["STRAT-*-review.md", "RHAISTRAT-*-review.md"]:
        for path in sorted(glob.glob(os.path.join(artifacts_dir, "strat-reviews", pattern))):
            if path.endswith("-review-comment.md"):
                continue
            try:
                meta, body = read_frontmatter(path)
                strat_id = meta.get("strat_id", Path(path).stem.replace("-review", ""))
                reviews[strat_id] = {"meta": meta, "body": body, "path": path}
            except Exception as e:
                print(f"Warning: failed to read {path}: {e}", file=sys.stderr)

    for pattern in ["STRAT-*-review-comment.md", "RHAISTRAT-*-review-comment.md"]:
        for path in sorted(glob.glob(os.path.join(artifacts_dir, "strat-reviews", pattern))):
            try:
                with open(path, encoding="utf-8") as f:
                    body = f.read()
                strat_id = Path(path).stem.replace("-review-comment", "")
                review_comments[strat_id] = body
            except Exception as e:
                print(f"Warning: failed to read {path}: {e}", file=sys.stderr)

    # Load skipped RFEs
    skipped = []
    pending_review = []
    skipped_path = os.path.join(artifacts_dir, "strat-skipped.md")
    if os.path.exists(skipped_path):
        with open(skipped_path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line.startswith("|") and not line.startswith("| RFE") and not line.startswith("|--"):
                    cols = [c.strip() for c in line.split("|")[1:-1]]
                    if len(cols) >= 4:
                        reason = cols[2]
                        entry = {
                            "rfe_key": cols[0],
                            "title": cols[1],
                            "reason": reason,
                            "run": cols[3],
                        }
                        if "already processed" in reason:
                            if "needs-attention" in reason:
                                strat_match = re.match(r'(\S+)\s+already processed', reason)
                                entry["strat_key"] = strat_match.group(1) if strat_match else ""
                                pending_review.append(entry)
                        else:
                            skipped.append(entry)

    return tasks, reviews, review_comments, skipped, pending_review

def md_to_html(md_text):
    """Minimal markdown to HTML conversion for rendering in report."""
    lines = md_text.split("\n")
    html_lines = []
    in_list = False
    in_code = False
    in_table = False
    code_block = []
    table_rows = []

    def flush_table():
        nonlocal in_table, table_rows
        if not table_rows:
            return
        html_lines.append('<table>')
        for idx, row_cells in enumerate(table_rows):
            tag = "th" if idx == 0 else "td"
            html_lines.append("<tr>")
            for cell in row_cells:
                html_lines.append(f"<{tag}>{inline_format(cell.strip())}</{tag}>")
            html_lines.append("</tr>")
        html_lines.append("</table>")
        table_rows = []
        in_table = False

    for line in lines:
        # Code blocks
        if line.strip().startswith("```"):
            if in_table:
                flush_table()
            if in_code:
                html_lines.append("<pre><code>" + escape_html("\n".join(code_block)) + "</code></pre>")
                code_block = []
                in_code = False
            else:
                if in_list:
                    html_lines.append("</ul>")
                    in_list = False
                in_code = True
            continue

        if in_code:
            code_block.append(line)
            continue

        stripped = line.strip()

        # Markdown table rows (lines starting and ending with |)
        if stripped.startswith("|") and stripped.endswith("|"):
            # Skip separator rows like |---|---|---|
            if re.match(r'^\|[\s\-:|]+\|$', stripped):
                continue
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            in_table = True
            cells = [c for c in stripped.split("|")[1:-1]]
            table_rows.append(cells)
            continue

        # If we were in a table and hit a non-table line, flush it
        if in_table:
            flush_table()

        # Empty line
        if not stripped:
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append("")
            continue

        # Headings
        heading_match = re.match(r'^(#{1,6})\s+(.*)', line)
        if heading_match:
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            level = len(heading_match.group(1))
            text = inline_format(heading_match.group(2))
            html_lines.append(f"<h{level}>{text}</h{level}>")
            continue

        # List items
        list_match = re.match(r'^[\s]*[-*]\s+(.*)', line)
        if list_match:
            if not in_list:
                html_lines.append("<ul>")
                in_list = True
            html_lines.append(f"<li>{inline_format(list_match.group(1))}</li>")
            continue

        # Numbered list items
        num_match = re.match(r'^[\s]*\d+\.\s+(.*)', line)
        if num_match:
            if not in_list:
                html_lines.append("<ul>")
                in_list = True
            html_lines.append(f"<li>{inline_format(num_match.group(1))}</li>")
            continue

        # Regular paragraph
        if in_list:
            html_lines.append("</ul>")
            in_list = False
        html_lines.append(f"<p>{inline_format(stripped)}</p>")

    if in_table:
        flush_table()
    if in_list:
        html_lines.append("</ul>")
    if in_code:
        html_lines.append("<pre><code>" + escape_html("\n".join(code_block)) + "</code></pre>")

    return "\n".join(html_lines)

def escape_html(text):
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

def inline_format(text):
    text = escape_html(text)
    text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
    text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', text)
    text = re.sub(r'`(.+?)`', r'<code>\1</code>', text)
    return text

def verdict_class(verdict):
    if verdict in ("approve", "approved"):
        return "verdict-approve"
    elif verdict in ("revise", "needs revision", "needs_revision"):
        return "verdict-revise"
    elif verdict in ("reject", "rejected", "infeasible"):
        return "verdict-reject"
    elif verdict == "split":
        return "verdict-split"
    return "verdict-unknown"

def verdict_label(verdict):
    if verdict in ("approve", "approved"):
        return "Approve"
    elif verdict in ("revise", "needs revision", "needs_revision"):
        return "Revise"
    elif verdict in ("reject", "rejected", "infeasible"):
        return "Reject"
    elif verdict == "split":
        return "Split"
    return verdict or "—"

def is_approve(v):
    return v in ("approve", "approved")

def is_revise(v):
    return v in ("revise", "needs revision", "needs_revision")

def is_reject(v):
    return v in ("reject", "rejected", "infeasible")

def is_split(v):
    return v == "split"

def pct(n, total):
    return round(100 * n / total) if total > 0 else 0

def label_css_class(label):
    """Map a label to its CSS class."""
    cat = label_category(label)
    return {
        "provenance": "label-provenance",
        "gate": "label-gate",
        "escalation": "label-escalation",
        "exclusion": "label-escalation",
    }.get(cat, "label-provenance")

def render_label_badges(labels):
    """Render a list of labels as HTML badge spans."""
    parts = []
    for label in labels:
        css = label_css_class(label)
        parts.append(f'<span class="label-badge {css}">{escape_html(label)}</span>')
    return " ".join(parts)

def health_color(rate):
    """Green >=70%, yellow 40-70%, red <40%."""
    if rate >= 70:
        return "#3fb950"
    elif rate >= 40:
        return "#d29922"
    return "#f85149"

def generate_html(tasks, reviews, review_comments, skipped, pending_review, config, output_path, cost_data=None):
    """Generate the full HTML report."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Build rows
    rows = []
    for strat_id in sorted(tasks.keys()):
        task = tasks[strat_id]
        review = reviews.get(strat_id, {})
        meta = task["meta"]
        rev_meta = review.get("meta", {})
        reviewers = rev_meta.get("reviewers", {})
        source_rfe = meta.get("source_rfe", "")
        cfg = config.get(source_rfe, {})

        scores = rev_meta.get("scores", {})
        rows.append({
            "strat_id": strat_id,
            "title": meta.get("title", ""),
            "source_rfe": source_rfe,
            "priority": meta.get("priority", "—"),
            "status": meta.get("status", "—"),
            "size": cfg.get("size") or extract_size(task.get("body", "")),
            "baseline": cfg.get("baseline", False),
            "cross_component": False,
            "recommendation": rev_meta.get("recommendation", "—"),
            "needs_attention": rev_meta.get("needs_attention", False),
            "feasibility": reviewers.get("feasibility", "—"),
            "testability": reviewers.get("testability", "—"),
            "scope": reviewers.get("scope", "—"),
            "architecture": reviewers.get("architecture", "—"),
            "scores": {
                "feasibility": scores.get("feasibility"),
                "testability": scores.get("testability"),
                "scope": scores.get("scope"),
                "architecture": scores.get("architecture"),
                "total": scores.get("total"),
            } if scores else None,
            "rfe_body": split_strategy_body(task.get("body", ""))[0],
            "strategy_body": split_strategy_body(task.get("body", ""))[1],
            "comment_body": review_comments.get(strat_id, ""),
            "review_body": review.get("body", ""),
            "labels": compute_strat_labels(
                meta.get("status", ""),
                rev_meta.get("recommendation", ""),
                reviewers,
            ),
        })

    # --- Executive stats ---
    reviewed_rows = [r for r in rows if r["recommendation"] not in ("—", "")]
    total = len(rows)
    total_reviewed = len(reviewed_rows)
    approved = sum(1 for r in reviewed_rows if is_approve(r["recommendation"]))
    revise = sum(1 for r in reviewed_rows if is_revise(r["recommendation"]))
    reject = sum(1 for r in reviewed_rows if is_reject(r["recommendation"]))
    split = sum(1 for r in reviewed_rows if is_split(r["recommendation"]))
    baselines = sum(1 for r in rows if r["baseline"])

    approval_rate = pct(approved, total_reviewed)
    revision_rate = pct(revise, total_reviewed)

    # Per-dimension stats from numeric scores (0=fail, 1=needs work, 2=pass)
    dimensions = ["feasibility", "testability", "scope", "architecture"]
    dim_stats = {}
    for dim in dimensions:
        scored_vals = [r["scores"][dim] for r in reviewed_rows
                       if r.get("scores") and r["scores"].get(dim) is not None]
        dim_total = len(scored_vals)
        dim_pass = sum(1 for v in scored_vals if v == 2)
        dim_partial = sum(1 for v in scored_vals if v == 1)
        dim_fail = sum(1 for v in scored_vals if v == 0)
        dim_sum = sum(scored_vals)
        dim_max = dim_total * 2
        dim_stats[dim] = {
            "total": dim_total,
            "pass": dim_pass,
            "partial": dim_partial,
            "fail": dim_fail,
            "rate": pct(dim_sum, dim_max),
        }

    # Weakest dimension
    weakest_dim = min(dimensions, key=lambda d: dim_stats[d]["rate"])
    weakest_rate = dim_stats[weakest_dim]["rate"]
    strongest_dim = max(dimensions, key=lambda d: dim_stats[d]["rate"])
    strongest_rate = dim_stats[strongest_dim]["rate"]

    # Numeric score aggregates
    scored = [r for r in rows if r.get("scores") and r["scores"].get("total") is not None]
    has_scores = len(scored) > 0
    avg_total_score = round(sum(r["scores"]["total"] for r in scored) / len(scored), 1) if scored else None
    needs_attention = sum(1 for r in reviewed_rows if r.get("needs_attention", False))

    # Cost data
    cost = cost_data or {}
    cost_total = cost.get("total_usd")
    cost_per_strat = round(cost_total / total_reviewed, 2) if cost_total is not None and total_reviewed else None

    # Hero statement
    attention_count = revise + split + reject
    if approval_rate >= 70:
        hero_text = f"{approved} of {total_reviewed} strategies ready — pipeline is healthy"
    elif approval_rate >= 40:
        hero_text = f"{approved} of {total_reviewed} strategies ready — {attention_count} need attention"
    else:
        hero_text = f"Only {approved} of {total_reviewed} strategies ready — {weakest_dim} is the bottleneck ({weakest_rate}% pass)"
    hero_color = health_color(approval_rate)

    # --- Build dimension bars HTML ---
    dim_bars_html = ""
    for dim in dimensions:
        ds = dim_stats[dim]
        rate = ds["rate"]
        color = health_color(rate)
        pass_w = pct(ds["pass"], ds["total"]) if ds["total"] else 0
        partial_w = pct(ds["partial"], ds["total"]) if ds["total"] else 0
        fail_w = pct(ds["fail"], ds["total"]) if ds["total"] else 0
        dim_bars_html += f"""
        <div class="dim-row">
            <div class="dim-label">{dim.title()}</div>
            <div class="dim-bar-container">
                <div class="dim-bar-track">
                    <div class="dim-bar-seg" style="width:{pass_w}%;background:#3fb950;" title="{ds['pass']} scored 2/2"></div>
                    <div class="dim-bar-seg" style="width:{partial_w}%;background:#d29922;" title="{ds['partial']} scored 1/2"></div>
                    <div class="dim-bar-seg" style="width:{fail_w}%;background:#f85149;" title="{ds['fail']} scored 0/2"></div>
                </div>
            </div>
            <div class="dim-rate" style="color:{color}">{rate}%</div>
        </div>"""

    # --- Build verdict grid HTML ---
    def score_style(score):
        if score == 2:
            return "background:#23302a;border-color:#3fb950;color:#3fb950"
        elif score == 1:
            return "background:#2d2400;border-color:#d29922;color:#d29922"
        elif score == 0:
            return "background:#2d1418;border-color:#f85149;color:#f85149"
        return "background:#161b22;border-color:#30363d;color:#6e7681"

    def verdict_cell_style(v):
        if is_approve(v):
            return "background:#23302a;border-color:#3fb950"
        elif is_revise(v):
            return "background:#2d2400;border-color:#d29922"
        elif is_split(v):
            return "background:#2d1a0d;border-color:#f78166"
        elif is_reject(v):
            return "background:#2d1418;border-color:#f85149"
        return "background:#161b22;border-color:#30363d"

    grid_html = ""
    for row in rows:
        rec = row["recommendation"]
        rec_cls = verdict_class(rec)
        sc = row.get("scores")
        cells = ""
        if sc:
            for dim in dimensions:
                v = sc.get(dim)
                text = f"{v}/2" if v is not None else "—"
                cells += f'<div class="grid-cell" style="{score_style(v)}" title="{dim.title()}: {text}">{text}</div>'
            total = sc.get("total")
            total_pct = round(total / 8 * 100) if total is not None else 0
            cells += f'<div class="grid-cell" style="color:{health_color(total_pct)};font-weight:600" title="Total: {total}/8">{total}/8</div>'
        else:
            for dim in dimensions:
                v = row[dim]
                cells += f'<div class="grid-cell" style="{verdict_cell_style(v)}" title="{dim.title()}: {v}"></div>'
            cells += '<div class="grid-cell" style="color:#6e7681">—</div>'
        strat_short = row["strat_id"].replace("STRAT-", "")
        grid_html += f"""
        <div class="grid-row">
            <div class="grid-id">STRAT-{escape_html(strat_short)}</div>
            {cells}
            <div class="grid-verdict {rec_cls}">{verdict_label(rec)}</div>
        </div>"""

    skipped_count = len(skipped)
    skipped_tab = (
        "" if not skipped else
        '<div class="nav-tab" onclick="switchPage('
        "'skipped'" ')">Skipped (%d)</div>' % skipped_count
    )
    pending_tab = (
        "" if not pending_review else
        '<div class="nav-tab" onclick="switchPage('
        "'pending'" ')">Pending Review (%d)</div>' % len(pending_review)
    )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Strategy Pipeline Report</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0d1117; color: #c9d1d9; padding: 24px; }}
.header {{ margin-bottom: 32px; }}
.header h1 {{ font-size: 28px; color: #f0f6fc; margin-bottom: 8px; }}
.header .subtitle {{ color: #8b949e; font-size: 14px; }}

/* Hero section */
.hero {{ background: #161b22; border: 1px solid #30363d; border-radius: 12px; padding: 32px; margin-bottom: 24px; text-align: center; }}
.hero-statement {{ font-size: 28px; font-weight: 700; margin-bottom: 8px; }}
.hero-sub {{ color: #8b949e; font-size: 14px; }}

/* KPI cards */
.kpi-grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 32px; }}
.kpi {{ background: #161b22; border: 1px solid #30363d; border-radius: 10px; padding: 20px 24px; text-align: center; }}
.kpi .kpi-value {{ font-size: 36px; font-weight: 700; line-height: 1.1; }}
.kpi .kpi-label {{ font-size: 12px; color: #8b949e; text-transform: uppercase; letter-spacing: 0.5px; margin-top: 6px; }}
.kpi .kpi-detail {{ font-size: 12px; color: #6e7681; margin-top: 4px; }}

/* Dimension breakdown */
.dim-section {{ background: #161b22; border: 1px solid #30363d; border-radius: 10px; padding: 24px; margin-bottom: 24px; }}
.dim-section h3 {{ color: #f0f6fc; font-size: 16px; margin-bottom: 16px; }}
.dim-row {{ display: flex; align-items: center; gap: 12px; margin-bottom: 12px; }}
.dim-label {{ width: 110px; font-size: 13px; color: #8b949e; text-align: right; flex-shrink: 0; }}
.dim-bar-container {{ flex: 1; }}
.dim-bar-track {{ display: flex; height: 24px; border-radius: 6px; overflow: hidden; background: #21262d; }}
.dim-bar-seg {{ transition: width 0.3s ease; }}
.dim-rate {{ width: 48px; font-size: 14px; font-weight: 700; text-align: right; flex-shrink: 0; }}

/* Verdict grid */
.grid-section {{ background: #161b22; border: 1px solid #30363d; border-radius: 10px; padding: 24px; margin-bottom: 24px; }}
.grid-section h3 {{ color: #f0f6fc; font-size: 16px; margin-bottom: 8px; }}
.grid-legend {{ display: flex; gap: 16px; margin-bottom: 16px; font-size: 12px; color: #8b949e; }}
.grid-legend-item {{ display: flex; align-items: center; gap: 4px; }}
.grid-legend-swatch {{ width: 12px; height: 12px; border-radius: 3px; border: 2px solid; }}
.grid-header {{ display: flex; align-items: center; gap: 4px; padding: 0 0 8px; border-bottom: 1px solid #21262d; margin-bottom: 8px; }}
.grid-header-id {{ width: 90px; font-size: 11px; color: #6e7681; text-transform: uppercase; }}
.grid-header-dim {{ width: 40px; text-align: center; font-size: 10px; color: #6e7681; text-transform: uppercase; }}
.grid-header-verdict {{ width: 72px; text-align: right; font-size: 11px; color: #6e7681; text-transform: uppercase; }}
.grid-row {{ display: flex; align-items: center; gap: 4px; padding: 4px 0; }}
.grid-id {{ width: 90px; font-size: 13px; color: #c9d1d9; font-weight: 500; }}
.grid-cell {{ width: 40px; height: 24px; border-radius: 4px; border: 2px solid; display: flex; align-items: center; justify-content: center; font-size: 11px; font-weight: 600; }}
.grid-verdict {{ width: 72px; text-align: right; font-size: 12px; font-weight: 600; }}

/* Summary panels */
.two-col {{ display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin-bottom: 24px; }}
@media (max-width: 900px) {{
    .kpi-grid {{ grid-template-columns: repeat(2, 1fr); }}
    .two-col {{ grid-template-columns: 1fr; }}
}}

/* Legacy styles (table, details, etc.) */
table {{ width: 100%; border-collapse: collapse; background: #161b22; border-radius: 8px; overflow: hidden; margin-bottom: 24px; }}
thead {{ background: #21262d; }}
th {{ text-align: left; padding: 12px 16px; font-size: 12px; color: #8b949e; text-transform: uppercase; letter-spacing: 0.5px; font-weight: 600; border-bottom: 1px solid #30363d; }}
td {{ padding: 12px 16px; border-bottom: 1px solid #21262d; font-size: 14px; }}
tr:hover {{ background: #1c2128; }}
tr.clickable {{ cursor: pointer; }}
.verdict-approve {{ color: #3fb950; font-weight: 600; }}
.verdict-revise {{ color: #d29922; font-weight: 600; }}
.verdict-reject {{ color: #f85149; font-weight: 600; }}
.verdict-split {{ color: #f78166; font-weight: 600; }}
.verdict-unknown {{ color: #8b949e; }}
.badge {{ display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; }}
.badge-baseline {{ background: #1f3a5f; color: #58a6ff; }}
.badge-cross {{ background: #3d2e00; color: #d29922; }}
.badge-size {{ background: #21262d; color: #8b949e; border: 1px solid #30363d; }}
.detail-panel {{ display: none; background: #0d1117; border: 1px solid #30363d; border-radius: 8px; margin: 8px 16px 16px; padding: 24px; }}
.detail-panel.open {{ display: block; }}
.detail-panel h2 {{ color: #f0f6fc; font-size: 20px; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 1px solid #21262d; }}
.detail-panel h3 {{ color: #c9d1d9; font-size: 16px; margin: 16px 0 8px; }}
.detail-panel h4 {{ color: #8b949e; font-size: 14px; margin: 12px 0 6px; }}
.detail-panel p {{ line-height: 1.6; margin-bottom: 8px; }}
.detail-panel ul {{ padding-left: 24px; margin-bottom: 8px; }}
.detail-panel li {{ line-height: 1.6; margin-bottom: 4px; }}
.detail-panel code {{ background: #21262d; padding: 2px 6px; border-radius: 4px; font-size: 13px; }}
.detail-panel pre {{ background: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 16px; overflow-x: auto; margin: 8px 0; }}
.detail-panel pre code {{ background: none; padding: 0; }}
.detail-tabs {{ display: flex; gap: 0; margin-bottom: 16px; border-bottom: 1px solid #30363d; }}
.detail-tab {{ padding: 8px 16px; cursor: pointer; color: #8b949e; font-size: 14px; border-bottom: 2px solid transparent; }}
.detail-tab:hover {{ color: #c9d1d9; }}
.detail-tab.active {{ color: #f0f6fc; border-bottom-color: #f78166; }}
.tab-content {{ display: none; }}
.tab-content.active {{ display: block; }}
.expand-icon {{ color: #8b949e; transition: transform 0.2s; display: inline-block; margin-right: 8px; }}
.expand-icon.open {{ transform: rotate(90deg); }}
.footer {{ margin-top: 32px; padding-top: 16px; border-top: 1px solid #21262d; color: #484f58; font-size: 12px; }}
.nav-tabs {{ display: flex; gap: 0; margin-bottom: 24px; border-bottom: 2px solid #21262d; }}
.nav-tab {{ padding: 12px 24px; cursor: pointer; color: #8b949e; font-size: 15px; font-weight: 600; border-bottom: 2px solid transparent; margin-bottom: -2px; transition: all 0.2s; }}
.nav-tab:hover {{ color: #c9d1d9; background: #161b22; }}
.nav-tab.active {{ color: #f0f6fc; border-bottom-color: #f78166; }}
.nav-page {{ display: none; }}
.nav-page.active {{ display: block; }}
.pipeline {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 24px; position: relative; }}
.pipeline h2 {{ color: #f0f6fc; font-size: 16px; margin-bottom: 16px; flex-shrink: 0; }}
.pipeline .mermaid {{ cursor: grab; }}
.pipeline .mermaid:active {{ cursor: grabbing; }}
.zoom-controls {{ position: absolute; top: 16px; right: 16px; display: flex; gap: 4px; z-index: 10; }}
.zoom-btn {{ background: #21262d; border: 1px solid #30363d; color: #c9d1d9; width: 32px; height: 32px; border-radius: 6px; cursor: pointer; font-size: 16px; display: flex; align-items: center; justify-content: center; }}
.zoom-btn:hover {{ background: #30363d; color: #f0f6fc; }}
.diagram-container {{ overflow: auto; position: relative; }}
.diagram-inner {{ transform-origin: 0 0; transition: transform 0.1s ease; display: flex; align-items: center; justify-content: center; padding: 24px 0; }}
.diagram-inner .mermaid {{ font-size: 16px; }}

/* Pipeline labels */
.label-bar {{ display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 16px; }}
.label-badge {{ display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 11px; font-weight: 600; }}
.label-provenance {{ background: #1c2333; color: #8b949e; }}
.label-stage {{ background: #0d419d; color: #58a6ff; }}
.label-gate {{ background: #23302a; color: #3fb950; }}
.label-gate-pending {{ background: #2d2400; color: #d29922; }}
.label-escalation {{ background: #2d1418; color: #f85149; }}
.label-legend {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 20px; margin-top: 24px; }}
.label-legend h3 {{ color: #f0f6fc; font-size: 14px; margin-bottom: 12px; }}
.label-legend table {{ margin-bottom: 0; }}
.label-legend td, .label-legend th {{ font-size: 12px; padding: 6px 12px; }}
</style>
</head>
<body>

<div class="header">
    <h1>Strategy Pipeline Report</h1>
    <div class="subtitle">Generated {timestamp} | {total} strategies processed</div>
</div>

<div class="nav-tabs">
    <div class="nav-tab active" onclick="switchPage('summary')">Summary</div>
    <div class="nav-tab" onclick="switchPage('details')">Details</div>
    {skipped_tab}
    {pending_tab}
    <div class="nav-tab" onclick="switchPage('pipeline')">Pipeline</div>
</div>

<div class="nav-page active" id="page-summary">

<!-- Hero statement -->
<div class="hero">
    <div class="hero-statement" style="color:{hero_color}">{escape_html(hero_text)}</div>
    <div class="hero-sub">Strategy readiness across {total_reviewed} reviewed strategies | Generated {timestamp}</div>
</div>

<!-- KPI cards -->
<div class="kpi-grid" style="grid-template-columns: repeat(6, 1fr);">
    <div class="kpi">
        <div class="kpi-value" style="color:#f0f6fc">{total_reviewed}</div>
        <div class="kpi-label">Strategies Reviewed</div>
        <div class="kpi-detail">{total} total processed</div>
    </div>
    <div class="kpi">
        <div class="kpi-value" style="color:{health_color(approval_rate)}">{approval_rate}%</div>
        <div class="kpi-label">Approval Rate</div>
        <div class="kpi-detail">{approved} of {total_reviewed} approved</div>
    </div>
    <div class="kpi">
        <div class="kpi-value" style="color:{health_color(int(avg_total_score / 8 * 100) if avg_total_score else 0)}">{avg_total_score if avg_total_score is not None else "—"}<span style="font-size:16px;color:#6e7681">/8</span></div>
        <div class="kpi-label">Avg Score</div>
        <div class="kpi-detail">{"Rubric: F+T+S+A (0-2 each)" if has_scores else "Scoring not yet enabled"}</div>
    </div>
    <div class="kpi">
        <div class="kpi-value" style="color:#f85149">{needs_attention}</div>
        <div class="kpi-label">Needs Attention</div>
        <div class="kpi-detail">{"Human review required" if needs_attention > 0 else "All clear"}</div>
    </div>
    <div class="kpi">
        <div class="kpi-value" style="color:#d29922">{revise + split}</div>
        <div class="kpi-label">Revise / Split</div>
        <div class="kpi-detail">{revise} revise, {split} split</div>
    </div>
    <div class="kpi">
        <div class="kpi-value" style="color:#f85149">{reject}</div>
        <div class="kpi-label">Rejected</div>
        <div class="kpi-detail">{"Fundamental problems" if reject > 0 else "None rejected"}</div>
    </div>
    <div class="kpi">
        <div class="kpi-value" style="color:{health_color(weakest_rate)}">{weakest_rate}%</div>
        <div class="kpi-label">Weakest: {weakest_dim.title()}</div>
        <div class="kpi-detail">Strongest: {strongest_dim.title()} ({strongest_rate}%)</div>
    </div>
    {"" if not skipped else '<div class="kpi"><div class="kpi-value" style="color:#d29922">' + str(len(skipped)) + '</div><div class="kpi-label">Skipped</div><div class="kpi-detail">Missing required labels</div></div>'}
    {"" if not pending_review else '<div class="kpi"><div class="kpi-value" style="color:#f0883e">' + str(len(pending_review)) + '</div><div class="kpi-label">Pending Review</div><div class="kpi-detail">Awaiting human review</div></div>'}
    {"" if cost_total is None else '<div class="kpi"><div class="kpi-value" style="color:#bc8cff">$' + f'{cost_total:.2f}' + '</div><div class="kpi-label">Run Cost</div><div class="kpi-detail">$' + f'{cost_per_strat:.2f}' + '/strategy</div></div>'}
</div>

<!-- Two-column: Dimension breakdown + Verdict grid -->
<div class="two-col">
    <div class="dim-section">
        <h3>Review Dimensions</h3>
        {dim_bars_html}
        <div style="display:flex;gap:16px;margin-top:12px;font-size:11px;color:#6e7681">
            <span><span style="display:inline-block;width:10px;height:10px;background:#3fb950;border-radius:2px;margin-right:4px"></span>2/2 (pass)</span>
            <span><span style="display:inline-block;width:10px;height:10px;background:#d29922;border-radius:2px;margin-right:4px"></span>1/2 (gaps)</span>
            <span><span style="display:inline-block;width:10px;height:10px;background:#f85149;border-radius:2px;margin-right:4px"></span>0/2 (fail)</span>
        </div>
    </div>
    <div class="grid-section">
        <h3>Per-Strategy Scores</h3>
        <div class="grid-header">
            <div class="grid-header-id">Strategy</div>
            <div class="grid-header-dim">Feas</div>
            <div class="grid-header-dim">Test</div>
            <div class="grid-header-dim">Scope</div>
            <div class="grid-header-dim">Arch</div>
            <div class="grid-header-dim">Total</div>
            <div class="grid-header-verdict">Verdict</div>
        </div>
        {grid_html}
    </div>
</div>

<!-- Full summary table -->
<table>
<thead>
<tr>
    <th>Strat ID</th>
    <th>Title</th>
    <th>Source RFE</th>
    <th>Size</th>
    <th>F</th>
    <th>T</th>
    <th>S</th>
    <th>A</th>
    <th>Score</th>
    <th>Verdict</th>
    <th>Attention</th>
</tr>
</thead>
<tbody>
"""

    for i, row in enumerate(rows):
        badges = ""
        if row["baseline"]:
            badges += ' <span class="badge badge-baseline">baseline</span>'
        if row["cross_component"]:
            badges += ' <span class="badge badge-cross">cross-component</span>'

        sc = row.get("scores")
        if sc:
            score_cells = ""
            for dim in dimensions:
                v = sc.get(dim)
                score_cells += f'<td style="{score_style(v)};text-align:center;font-weight:600">{v if v is not None else "—"}</td>'
            total = sc.get("total")
            total_pct = round(total / 8 * 100) if total is not None else 0
            score_cells += f'<td style="color:{health_color(total_pct)};font-weight:600;text-align:center">{total}/8</td>'
        else:
            score_cells = f'<td class="{verdict_class(row["feasibility"])}">{verdict_label(row["feasibility"])}</td>'
            score_cells += f'<td class="{verdict_class(row["testability"])}">{verdict_label(row["testability"])}</td>'
            score_cells += f'<td class="{verdict_class(row["scope"])}">{verdict_label(row["scope"])}</td>'
            score_cells += f'<td class="{verdict_class(row["architecture"])}">{verdict_label(row["architecture"])}</td>'
            score_cells += '<td style="color:#6e7681;text-align:center">—</td>'

        attention_html = '<span style="color:#f85149;font-weight:600">&#9679; Yes</span>' if row.get("needs_attention") else '<span style="color:#3fb950">&#10003;</span>'

        html += f"""<tr>
    <td><strong>{escape_html(row["strat_id"])}</strong></td>
    <td>{escape_html(row["title"])}{badges}</td>
    <td>{escape_html(row["source_rfe"])}</td>
    <td><span class="badge badge-size">{escape_html(str(row["size"]))}</span></td>
    {score_cells}
    <td class="{verdict_class(row["recommendation"])}">{verdict_label(row["recommendation"])}</td>
    <td style="text-align:center">{attention_html}</td>
</tr>
"""

    html += f"""</tbody>
</table>
</div><!-- end page-summary -->

<div class="nav-page" id="page-pipeline">
<div class="pipeline">
    <h2>RHAI Agentic SDLC Pipeline</h2>
    <div class="zoom-controls">
        <button class="zoom-btn" onclick="zoomDiagram(1.2)" title="Zoom in">+</button>
        <button class="zoom-btn" onclick="zoomDiagram(0.8)" title="Zoom out">&minus;</button>
        <button class="zoom-btn" onclick="resetDiagram()" title="Reset">&#8634;</button>
    </div>
    <div class="diagram-container" id="diagram-container">
    <div class="diagram-inner" id="diagram-inner">
    <pre class="mermaid">
graph LR
    subgraph P1["Phase 1: RFE Assessment"]
        A[rfe.create] --> B[rfe.review]
        B --> C[rfe.auto-fix]
        C --> D[rfe.submit]
    end

    D -->|"Auto job\\ntrigger"| E0

    subgraph P2["Phase 2: Strategy Refinement"]

        subgraph SC["strategy-create"]
            E0["strategy-create"] --> GATE{{{{Pipeline label gate\\nstrat-creator-3.5 +\\nrfe-creator-autofix-rubric-pass\\nor tech-reviewed}}}}
            GATE -->|"Fail"| SKIP["Skipped RFEs\\nstrat-skipped.md"]
            GATE -->|"Pass"| E1["Fetch RFE\\nfrom Jira"]
            E1 --> E2["Check existing\\nSTRATs via Cloners"]
            E2 --> EG{{{{"Pipeline label gate\\nSkip if rubric-pass\\nor needs-attention"}}}}
            EG -->|"Fail"| ESKIP["Skipped STRATs"]
            EG -->|"Pass"| E3["Clone or import\\nRHAISTRAT from Jira"]
            E3 --> E4["Save originals\\n& fetch comments"]
            E4 --> E5["Create strategy\\nstubs"]
            E5 --> E6["Add label\\nstrat-creator-auto-created"]
        end

        E6 --> SF

        subgraph SR["strategy-refine"]
            SF["strategy-refine"] --> FG{{{{"Pipeline label gate\\nSkip if rubric-pass\\nor needs-attention"}}}}
            FG -->|"Fail"| FSKIP["Skipped STRATs"]
            FG -->|"Pass"| F0["Fetch arch\\ncontext"]
            F0 --> F1["HOW context\\n&#8226; removed-context (RFE)\\n&#8226; Staff Eng Input\\n&#8226; Arch overlays"]
            F1 --> F2["Technical approach\\n& components"]
            F2 --> F3["Dependencies,\\nNFRs & effort"]
            F3 --> F5["Push strategy\\nto Jira"]
            F5 --> F4["Add label\\nstrat-creator-auto-refined"]
        end

        F4 --> SRV

        subgraph SV["strategy-review"]
            SRV["strategy-review"] --> RG{{{{"Pipeline label gate\\nSkip if rubric-pass\\nor needs-attention"}}}}
            RG -->|"Fail"| RSKIP["Skipped STRATs"]
            RG -->|"Pass"| R1[feasibility]
            RG -->|"Pass"| R2[testability]
            RG -->|"Pass"| R3[scope]
            RG -->|"Pass"| R4[architecture]
            RG -->|"Pass"| R5["future:\\nUX, migration,\\ndeps, ..."]
            R1 & R2 & R3 & R4 & R5 --> SC1["assess-strat\\nscorer agents\\nF/T/S/A 0-2"]
            SC1 --> SCRIPTS["parse_results.py &#8594; apply_scores.py\\n(deterministic verdicts)"]
            SCRIPTS --> CON["Write review\\nscores + prose"]
            CON --> JIRA["Attach review to Jira\\n& post summary\\nas comment"]
            JIRA --> Q{{{{&#8805;6/8\\nno zeros?}}}}
            Q -->|"APPROVE"| LA["Add label\\nstrat-creator-rubric-pass"]
            Q -->|"REVISE / REJECT"| LR["Add label\\nstrat-creator-needs-attention"]
        end

        LA --> PA{{"AI Strategy HOW\\nReady\\n(&#128100; review required)"}}
        LR --> HR["&#128100; Human Review\\nStaff Eng or Architect"]

        HR -->|"Path A: Update\\narchitecture context"| RL["Remove label\\nneeds-attention"]
        HR -->|"Path B: Edit\\nStaff Engineer / SME Input"| RL
        RL -->|"Re-trigger pipeline\\nvia CI or strategy-submit"| SF

        HR -->|"Path C: /strategy-pull\\nthen local refine/review"| LP["&#128100; Local\\nRefine/Review Loop"]
        LP -->|"/strategy-push"| RL

        PA -->|"/strategy-pull"| LP2["&#128100; Local\\nReview Loop"]
        LP2 -->|"/strategy-signoff"| SO["Add label\\nstrat-creator-human-sign-off"]
    end

    SO --> FR

    subgraph P3["Phase 3: Feature Dev"]
        FR[feature.ready] --> J[Feature Ready]
        J --> K[Prioritize]
        K --> L[AI-Assisted Dev]
        L --> M[PR Review]
    end

    style A fill:#2d6a2d,color:#fff
    style B fill:#2d6a2d,color:#fff
    style C fill:#2d6a2d,color:#fff
    style D fill:#2d6a2d,color:#fff
    style GATE fill:#1f3a5f,color:#58a6ff,stroke:#58a6ff
    style SKIP fill:#3d1f00,color:#d29922,stroke:#d29922
    style EG fill:#1f3a5f,color:#58a6ff,stroke:#58a6ff
    style ESKIP fill:#3d1f00,color:#d29922,stroke:#d29922
    style E0 fill:#2d6a2d,color:#fff
    style E6 fill:#6e40c9,color:#fff
    style E1 fill:#c77d1a,color:#fff
    style E2 fill:#c77d1a,color:#fff
    style E3 fill:#c77d1a,color:#fff
    style E4 fill:#c77d1a,color:#fff
    style E5 fill:#c77d1a,color:#fff
    style SF fill:#2d6a2d,color:#fff
    style FSKIP fill:#3d1f00,color:#d29922,stroke:#d29922
    style FG fill:#1f3a5f,color:#58a6ff,stroke:#58a6ff
    style F0 fill:#c77d1a,color:#fff
    style F1 fill:#c77d1a,color:#fff
    style F2 fill:#c77d1a,color:#fff
    style F3 fill:#c77d1a,color:#fff
    style F5 fill:#c77d1a,color:#fff
    style F4 fill:#6e40c9,color:#fff
    style SC1 fill:#c77d1a,color:#fff
    style SCRIPTS fill:#1f6feb,color:#fff
    style R1 fill:#c77d1a,color:#fff
    style R2 fill:#c77d1a,color:#fff
    style R3 fill:#c77d1a,color:#fff
    style R4 fill:#c77d1a,color:#fff
    style R5 fill:#555,color:#8b949e,stroke:#6e7681,stroke-dasharray:5
    style CON fill:#c77d1a,color:#fff
    style JIRA fill:#c77d1a,color:#fff
    style SRV fill:#2d6a2d,color:#fff
    style RG fill:#1f3a5f,color:#58a6ff,stroke:#58a6ff
    style RSKIP fill:#3d1f00,color:#d29922,stroke:#d29922
    style Q fill:#1f3a5f,color:#58a6ff,stroke:#58a6ff
    style LA fill:#6e40c9,color:#fff
    style LR fill:#6e40c9,color:#fff
    style PA fill:#2d6a2d,color:#fff,stroke:#3fb950,stroke-width:3px
    style HR fill:#3d1f00,color:#f0883e,stroke:#f0883e
    style RL fill:#6e40c9,color:#fff
    style FR fill:#555,color:#fff
    style J fill:#555,color:#fff
    style K fill:#555,color:#fff
    style L fill:#555,color:#fff
    style M fill:#555,color:#fff
    </pre>
    </div>
    </div>

    <div class="label-legend">
    <h3>Pipeline Labels (strat-creator-*)</h3>
    <table>
    <thead><tr><th>Label</th><th>Category</th><th>Applied When</th></tr></thead>
    <tbody>
    <tr><td><span class="label-badge label-provenance">strat-creator-auto-created</span></td><td>Provenance</td><td>strategy.create generates the RHAISTRAT ticket</td></tr>
    <tr><td><span class="label-badge label-provenance">strat-creator-auto-refined</span></td><td>Provenance</td><td>strategy.refine enriches with technical approach</td></tr>
    <tr><td><span class="label-badge label-provenance">strat-creator-auto-revised</span></td><td>Provenance</td><td>strategy.revise modifies content after review feedback</td></tr>
    <tr><td><span class="label-badge label-gate">strat-creator-rubric-pass</span></td><td>Gate</td><td>Approved; excluded from re-processing in future runs</td></tr>
    <tr><td><span class="label-badge label-escalation">strat-creator-needs-attention</span></td><td>Escalation</td><td>REVISE / REJECT &#8212; human review required</td></tr>
    <tr><td><span class="label-badge label-escalation">strat-creator-ignore</span></td><td>Exclusion</td><td>Permanent exclusion from pipeline (human-set only)</td></tr>
    </tbody>
    </table>
    </div>

</div>
</div><!-- end page-pipeline -->

<div class="nav-page" id="page-details">

<table>
<thead>
<tr>
    <th></th>
    <th>Strat ID</th>
    <th>Title</th>
    <th>Recommendation</th>
</tr>
</thead>
<tbody>
"""

    for i, row in enumerate(rows):
        badges = ""
        if row["baseline"]:
            badges += ' <span class="badge badge-baseline">baseline</span>'
        if row["cross_component"]:
            badges += ' <span class="badge badge-cross">cross-component</span>'

        html += f"""<tr class="clickable" onclick="toggleDetail({i})">
    <td><span class="expand-icon" id="icon-{i}">&#9654;</span></td>
    <td><strong>{escape_html(row["strat_id"])}</strong></td>
    <td>{escape_html(row["title"])}{badges}</td>
    <td class="{verdict_class(row["recommendation"])}">{verdict_label(row["recommendation"])}</td>
</tr>
<tr><td colspan="4" style="padding:0">
    <div class="detail-panel" id="detail-{i}">
        <h2>{escape_html(row["strat_id"])}: {escape_html(row["title"])}</h2>
        <div class="label-bar">{render_label_badges(row["labels"])}</div>
        <div class="detail-tabs">
            <div class="detail-tab active" onclick="switchTab({i}, 'rfe')">Original RFE</div>
            <div class="detail-tab" onclick="switchTab({i}, 'strategy')">Strategy (AI Generated)</div>
            <div class="detail-tab" onclick="switchTab({i}, 'comment')">Review Summary (Jira Comment)</div>
            <div class="detail-tab" onclick="switchTab({i}, 'review')">Detailed Review</div>
        </div>
        <div class="tab-content active" id="tab-{i}-rfe">
            {md_to_html(row["rfe_body"]) if row["rfe_body"] else "<em>No RFE content</em>"}
        </div>
        <div class="tab-content" id="tab-{i}-strategy">
            {md_to_html(row["strategy_body"]) if row["strategy_body"] else "<em>No strategy generated yet</em>"}
        </div>
        <div class="tab-content" id="tab-{i}-comment">
            {md_to_html(row["comment_body"]) if row["comment_body"] else "<em>No review comment available</em>"}
        </div>
        <div class="tab-content" id="tab-{i}-review">
            {md_to_html(row["review_body"])}
        </div>
    </div>
</td></tr>
"""

    html += f"""</tbody>
</table>
</div><!-- end page-details -->

"""

    # Skipped RFEs section
    if skipped:
        html += f"""<div class="nav-page" id="page-skipped">
    <div class="hero-sub" style="color:#d29922; margin-bottom: 16px;">
        {len(skipped)} RFEs skipped due to missing required labels
    </div>
    <table>
        <thead><tr>
            <th>RFE Key</th>
            <th>Title</th>
            <th>Reason</th>
        </tr></thead>
        <tbody>
"""
        for s in skipped:
            html += f"""        <tr>
            <td>{escape_html(s["rfe_key"])}</td>
            <td>{escape_html(s["title"])}</td>
            <td style="color:#f85149">{escape_html(s["reason"])}</td>
        </tr>
"""
        html += """        </tbody>
    </table>
</div><!-- end page-skipped -->

"""

    # Pending Review section
    if pending_review:
        html += f"""<div class="nav-page" id="page-pending">
    <div class="hero-sub" style="color:#f0883e; margin-bottom: 16px;">
        {len(pending_review)} STRATs awaiting human review
    </div>
    <table>
        <thead><tr>
            <th>STRAT Key</th>
            <th>Source RFE</th>
            <th>Title</th>
        </tr></thead>
        <tbody>
"""
        for p in pending_review:
            html += f"""        <tr>
            <td><a href="https://redhat.atlassian.net/browse/{escape_html(p["strat_key"])}" style="color:#58a6ff">{escape_html(p["strat_key"])}</a></td>
            <td>{escape_html(p["rfe_key"])}</td>
            <td>{escape_html(p["title"])}</td>
        </tr>
"""
        html += """        </tbody>
    </table>
</div><!-- end page-pending -->

"""

    html += f"""<div class="footer">
    strat-creator pipeline | RHAI Agentic SDLC
</div>

<script>
let mermaidRendered = false;
function switchPage(page) {{
    document.querySelectorAll('.nav-page').forEach(p => p.classList.remove('active'));
    document.querySelectorAll('.nav-tab').forEach(t => t.classList.remove('active'));
    document.getElementById('page-' + page).classList.add('active');
    event.target.classList.add('active');
    if (page === 'pipeline' && !mermaidRendered) {{
        mermaidRendered = true;
        renderMermaid();
    }}
}}

function toggleDetail(i) {{
    const panel = document.getElementById('detail-' + i);
    const icon = document.getElementById('icon-' + i);
    panel.classList.toggle('open');
    icon.classList.toggle('open');
}}

function switchTab(i, tab) {{
    const tabs = document.querySelectorAll('#detail-' + i + ' .detail-tab');
    const contents = document.querySelectorAll('#detail-' + i + ' .tab-content');
    tabs.forEach(t => t.classList.remove('active'));
    contents.forEach(c => c.classList.remove('active'));
    document.getElementById('tab-' + i + '-' + tab).classList.add('active');
    event.target.classList.add('active');
}}
</script>

<script>
let diagramScale = 1;
let diagramX = 0, diagramY = 0;
let isDragging = false, startX, startY;

function zoomDiagram(factor) {{
    diagramScale *= factor;
    diagramScale = Math.max(0.3, Math.min(3, diagramScale));
    updateDiagramTransform();
}}

function resetDiagram() {{
    diagramScale = 1;
    diagramX = 0;
    diagramY = 0;
    updateDiagramTransform();
}}

function updateDiagramTransform() {{
    const inner = document.getElementById('diagram-inner');
    inner.style.transform = `translate(${{diagramX}}px, ${{diagramY}}px) scale(${{diagramScale}})`;
}}

const container = document.getElementById('diagram-container');
container.addEventListener('wheel', (e) => {{
    e.preventDefault();
    zoomDiagram(e.deltaY < 0 ? 1.1 : 0.9);
}}, {{ passive: false }});

container.addEventListener('mousedown', (e) => {{
    isDragging = true;
    startX = e.clientX - diagramX;
    startY = e.clientY - diagramY;
}});

document.addEventListener('mousemove', (e) => {{
    if (!isDragging) return;
    diagramX = e.clientX - startX;
    diagramY = e.clientY - startY;
    const inner = document.getElementById('diagram-inner');
    inner.style.transition = 'none';
    updateDiagramTransform();
    inner.style.transition = 'transform 0.1s ease';
}});

document.addEventListener('mouseup', () => {{ isDragging = false; }});
</script>

<script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
    mermaid.initialize({{
        startOnLoad: false,
        theme: 'dark',
        flowchart: {{
            useMaxWidth: false,
            htmlLabels: true,
            curve: 'basis'
        }}
    }});

    // Deferred render — Mermaid can't measure inside display:none
    window.renderMermaid = async function() {{
        await mermaid.run();
        const svg = document.querySelector('.mermaid svg');
        const ctr = document.getElementById('diagram-container');
        if (svg && ctr) {{
            const svgRect = svg.getBoundingClientRect();
            const ctrRect = ctr.getBoundingClientRect();
            const scaleX = ctrRect.width / svgRect.width;
            const scaleY = ctrRect.height / svgRect.height;
            diagramScale = Math.min(scaleX, scaleY, 2) * 0.9;
            diagramX = (ctrRect.width - svgRect.width * diagramScale) / 2;
            diagramY = (ctrRect.height - svgRect.height * diagramScale) / 2;
            updateDiagramTransform();
        }}
    }};
</script>

</body>
</html>"""

    with open(output_path, "w") as f:
        f.write(html)
    print(f"Report generated: {output_path}")

def main():
    parser = argparse.ArgumentParser(description="Generate strategy pipeline HTML report")
    parser.add_argument("--output", "-o", default=None,
                        help="Output HTML file path (default: artifacts/reports/<timestamp>/report.html)")
    parser.add_argument("--config", "-c", default="config/test-rfes.yaml",
                        help="Test RFEs config file (default: config/test-rfes.yaml)")
    parser.add_argument("--artifacts", "-a", default="artifacts",
                        help="Artifacts directory (default: artifacts)")
    args = parser.parse_args()

    # Default output: timestamped folder
    if args.output is None:
        ts = datetime.now().strftime("%Y%m%d-%H%M%S")
        report_dir = os.path.join(args.artifacts, "reports", ts)
        os.makedirs(report_dir, exist_ok=True)
        output_path = os.path.join(report_dir, "report.html")
    else:
        output_path = args.output
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    # Load config
    config = {}
    if os.path.exists(args.config):
        try:
            config = load_yaml_config(args.config)
        except Exception as e:
            print(f"Warning: failed to read config: {e}", file=sys.stderr)

    # Load artifacts
    tasks, reviews, review_comments, skipped, pending_review = load_artifacts(args.artifacts)

    if not tasks and not skipped:
        print("Error: no strategy artifacts found in", args.artifacts, file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(tasks)} strategies, {len(reviews)} reviews, {len(review_comments)} review comments, {len(skipped)} skipped, {len(pending_review)} pending review")

    if not tasks:
        print("All RFEs were skipped, no report to generate.")
        sys.exit(0)

    # Load cost data from pipeline-data.json if available
    cost_data = None
    pdata_path = os.path.join(args.artifacts, "pipeline-data.json")
    if os.path.exists(pdata_path):
        try:
            with open(pdata_path, encoding="utf-8") as f:
                pdata = json.load(f)
            cost_data = pdata.get("cost")
        except Exception as e:
            print(f"Warning: failed to read pipeline-data.json: {e}", file=sys.stderr)

    generate_html(tasks, reviews, review_comments, skipped, pending_review, config, output_path, cost_data=cost_data)

if __name__ == "__main__":
    main()
