#!/usr/bin/env python3
"""Push the AI-generated Strategy section to a RHAISTRAT issue in Jira.

Reads the existing Jira description (preserving human-authored content),
then appends or replaces the "## Strategy (AI Generated by Agentic SDLC
Pipeline)" section with the locally refined version.

Usage:
    python3 scripts/push_strategy.py RHAISTRAT-1520 artifacts/strat-tasks/RHAISTRAT-1520.md

Environment variables:
    JIRA_SERVER  Jira server URL
    JIRA_USER    Jira username/email
    JIRA_TOKEN   Jira API token
"""

import argparse
import fcntl
import json
import os
import re
import stat
import sys
import tempfile
import threading
import urllib.error
from contextlib import contextmanager

from jira_utils import (
    add_attachment,
    adf_to_markdown,
    api_call_with_retry,
    attachment_sort_key,
    build_rfe_reference,
    get_issue,
    markdown_to_adf,
    require_env,
    strip_metadata,
    update_summary,
)

DRAFT_PREFIX = "[DRAFT] "

STRATEGY_HEADING = "## Strategy (AI Generated by Agentic SDLC Pipeline)"
STAFF_INPUT_HEADING = "## Staff Engineer / SME Input"
STAFF_INPUT_PATTERN = r'## Staff Engineer(?: / SME)? Input'
STAFF_INPUT_TEMPLATE = """## Staff Engineer / SME Input

*Add technical corrections, architectural direction, component preferences, or domain expertise below. \
Write in declarative, cumulative form — statements that remain valid across refinement iterations. \
This input takes priority over architecture context when they conflict. \
After review: address findings, then remove the needs-attention label from Jira.*"""

STRATEGY_ATTACHMENT_TEMPLATE = "{issue_key}-strategy.md"
ATTACHMENT_NOTICE = (
    "> **Note:** The full strategy exceeds Jira's description size limit "
    "and is stored as an attachment: `{filename}`. "
    "The TL;DR is shown below for quick reference."
)
ATTACHMENT_NOTICE_NO_TLDR = (
    "> **Note:** The full strategy exceeds Jira's description size limit "
    "and is stored as an attachment: `{filename}`."
)

_attachment_writer_locks = {}
_attachment_writer_locks_guard = threading.Lock()


def _reject_symlink_components(path):
    """Reject symlinked components in a lock path before opening it."""
    current = os.path.sep
    for component in os.path.abspath(path).split(os.path.sep):
        if not component:
            continue
        current = os.path.join(current, component)
        try:
            mode = os.lstat(current).st_mode
        except FileNotFoundError:
            continue
        if stat.S_ISLNK(mode):
            raise RuntimeError(
                f"Refusing symlinked lock path component: {current}")


def _ensure_private_directory(path, *, create):
    """Validate a user-owned directory with no group/world access."""
    _reject_symlink_components(path)
    try:
        info = os.lstat(path)
    except FileNotFoundError:
        if not create:
            raise RuntimeError(f"Lock directory does not exist: {path}")
        try:
            os.mkdir(path, 0o700)
        except FileExistsError:
            # Another writer may have created the directory between lstat and
            # mkdir; validate the resulting path below.
            pass
        info = os.lstat(path)

    if stat.S_ISLNK(info.st_mode) or not stat.S_ISDIR(info.st_mode):
        raise RuntimeError(f"Lock path is not a directory: {path}")
    getuid = getattr(os, "getuid", None)
    if getuid is not None and info.st_uid != getuid():
        raise RuntimeError(f"Lock directory is not user-owned: {path}")
    if stat.S_IMODE(info.st_mode) & 0o077:
        if not create:
            raise RuntimeError(f"Lock directory is not private: {path}")

        # The cache directory may be created by a base image with permissive
        # mode bits. Tighten only directories we own and are managing. Open
        # the directory without following symlinks, then chmod the descriptor
        # to avoid changing a raced replacement target.
        flags = os.O_RDONLY | getattr(os, "O_DIRECTORY", 0)
        flags |= getattr(os, "O_NOFOLLOW", 0)
        directory_fd = os.open(path, flags)
        try:
            current = os.fstat(directory_fd)
            if (current.st_dev, current.st_ino) != (info.st_dev, info.st_ino):
                raise RuntimeError(f"Lock directory changed during validation: {path}")
            if not stat.S_ISDIR(current.st_mode):
                raise RuntimeError(f"Lock path is not a directory: {path}")
            if getuid is not None and current.st_uid != getuid():
                raise RuntimeError(f"Lock directory is not user-owned: {path}")
            os.fchmod(directory_fd, 0o700)
            info = os.fstat(directory_fd)
        finally:
            os.close(directory_fd)
        if stat.S_IMODE(info.st_mode) & 0o077:
            raise RuntimeError(f"Lock directory is not private: {path}")


def _cache_attachment_lock_directory():
    """Return a private, user-owned cache directory for lock files."""
    cache_dir = os.path.join(os.path.expanduser("~"), ".cache")
    _ensure_private_directory(cache_dir, create=True)
    lock_dir = os.path.join(cache_dir, "strat-creator-locks")
    _ensure_private_directory(lock_dir, create=True)
    return lock_dir


def _attachment_lock_directory():
    """Return a private, user-owned runtime/cache directory for lock files."""
    runtime_dir = os.environ.get("XDG_RUNTIME_DIR")
    if runtime_dir:
        # Keep security failures hard: an untrusted runtime directory must not
        # be bypassed silently. A secure runtime directory can still be
        # unavailable in a restricted container, so fall back to the private
        # user cache when creating our child fails operationally.
        _ensure_private_directory(runtime_dir, create=False)
        lock_dir = os.path.join(runtime_dir, "strat-creator-locks")
        try:
            _ensure_private_directory(lock_dir, create=True)
            return lock_dir
        except OSError:
            pass
    return _cache_attachment_lock_directory()


def _open_attachment_lock(lock_path):
    """Open a lock file without following or truncating symlinks."""
    flags = os.O_RDWR | os.O_CREAT
    nofollow = getattr(os, "O_NOFOLLOW", 0)
    if nofollow:
        flags |= nofollow
    else:
        _reject_symlink_components(lock_path)
    fd = os.open(lock_path, flags, 0o600)
    try:
        info = os.fstat(fd)
        if not stat.S_ISREG(info.st_mode):
            raise RuntimeError(f"Lock path is not a regular file: {lock_path}")
        getuid = getattr(os, "getuid", None)
        if getuid is not None and info.st_uid != getuid():
            raise RuntimeError(f"Lock file is not user-owned: {lock_path}")
        if stat.S_IMODE(info.st_mode) & 0o077:
            raise RuntimeError(f"Lock file is not private: {lock_path}")
        return os.fdopen(fd, "a+", encoding="utf-8")
    except Exception:
        os.close(fd)
        raise


@contextmanager
def _attachment_writer_lock(issue_key):
    """Serialize attachment writes for an issue across local processes."""
    with _attachment_writer_locks_guard:
        thread_lock = _attachment_writer_locks.setdefault(
            issue_key, threading.Lock())

    lock_dir = _attachment_lock_directory()
    safe_issue_key = re.sub(r"[^A-Za-z0-9_.-]", "_", issue_key)
    lock_path = os.path.join(lock_dir, f"{safe_issue_key}.lock")

    with thread_lock, _open_attachment_lock(lock_path) as lock_file:
        fcntl.flock(lock_file, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(lock_file, fcntl.LOCK_UN)


def compute_synced_summary(current_summary, local_title):
    """Return the new Jira summary to sync to, or None if already in sync.

    `local_title` may itself carry the DRAFT_PREFIX (strategy frontmatter
    keeps it there until sign-off strips it from Jira), so both sides are
    compared and rebuilt on their bare (prefix-stripped) form to avoid
    double-prefixing when the Jira summary already has it too.
    """
    had_draft_prefix = current_summary.startswith(DRAFT_PREFIX)
    bare_current = current_summary[len(DRAFT_PREFIX):] if had_draft_prefix else current_summary
    bare_local_title = local_title[len(DRAFT_PREFIX):] if local_title.startswith(DRAFT_PREFIX) else local_title
    if bare_current == bare_local_title:
        return None
    return (DRAFT_PREFIX + bare_local_title) if had_draft_prefix else bare_local_title


def extract_source_rfe(content):
    """Extract source_rfe from YAML frontmatter before metadata is stripped."""
    match = re.match(r'^---\s*\n(.*?)\n---', content, re.DOTALL)
    if not match:
        return None
    rfe_match = re.search(r'source_rfe:\s*(RHAIRFE-\d+)', match.group(1))
    if not rfe_match:
        return None
    key = rfe_match.group(1)
    if key == "RHAIRFE-0":
        return None
    return key


def extract_title(content):
    """Extract title from YAML frontmatter before metadata is stripped."""
    match = re.match(r'^---\s*\n(.*?)\n---', content, re.DOTALL)
    if not match:
        return None
    title_match = re.search(r'^title:\s*(.+)$', match.group(1), re.MULTILINE)
    if not title_match:
        return None
    return title_match.group(1).strip().strip('"\'')


def extract_strategy_section(local_content):
    """Extract the Strategy section from a local strategy file."""
    match = re.search(
        r'(## Strategy \(AI Generated by Agentic SDLC Pipeline\).*?)(?=\n## (?!#)|$)',
        local_content,
        re.DOTALL,
    )
    if not match:
        return None
    return match.group(1).strip()


def extract_staff_input_section(local_content):
    """Extract the Staff Engineer / SME Input section from a local strategy file."""
    match = re.search(
        r'(' + STAFF_INPUT_PATTERN + r'.*?)(?=\n## (?!#)|$)',
        local_content,
        re.DOTALL,
    )
    if not match:
        return None
    return match.group(1).strip()


def extract_tldr_section(strategy_section):
    """Extract the ### TL;DR subsection from a strategy section."""
    match = re.search(
        r'(### TL;DR.*?)(?=\n### (?!#)|$)',
        strategy_section,
        re.DOTALL,
    )
    if not match:
        return None
    return match.group(1).strip()


def _build_description_stub(existing_md, strategy_section, staff_input_section,
                            attachment_filename):
    """Build a reduced description with TL;DR stub instead of full strategy."""
    if STRATEGY_HEADING in existing_md:
        before_strategy = existing_md[:existing_md.index(STRATEGY_HEADING)]
    else:
        before_strategy = existing_md

    # Remove any trailing Staff Engineer / SME Input from before_strategy
    # (it will be re-added at the end)
    staff_match = re.search(STAFF_INPUT_PATTERN, before_strategy)
    if staff_match:
        before_strategy = before_strategy[:staff_match.start()]

    tldr = extract_tldr_section(strategy_section)
    if tldr:
        notice = ATTACHMENT_NOTICE.format(filename=attachment_filename)
        stub_strategy = (
            f"{STRATEGY_HEADING}\n\n"
            f"{notice}\n\n"
            f"{tldr}\n"
        )
    else:
        notice = ATTACHMENT_NOTICE_NO_TLDR.format(filename=attachment_filename)
        stub_strategy = (
            f"{STRATEGY_HEADING}\n\n"
            f"{notice}\n"
        )

    parts = [before_strategy.rstrip()]
    parts.append(stub_strategy)

    if staff_input_section:
        parts.append(staff_input_section)
    elif not re.search(STAFF_INPUT_PATTERN, before_strategy):
        parts.append(STAFF_INPUT_TEMPLATE)

    return "\n\n".join(parts)


def update_description(server, user, token, issue_key, description_adf):
    """PUT only the description field (no summary change)."""
    body = {"fields": {"description": description_adf}}
    path = f"/issue/{issue_key}"
    api_call_with_retry(server, path, user, token, body=body, method="PUT")


def _find_strategy_attachment(attachments, issue_key):
    """Find the newest strategy attachment by naming convention."""
    filename = STRATEGY_ATTACHMENT_TEMPLATE.format(issue_key=issue_key)
    candidates = [att for att in attachments
                  if att.get("filename") == filename]
    return (max(candidates, key=attachment_sort_key)
            if candidates else None)


def _push_via_attachment(server, user, token, issue_key, existing_md,
                         strategy_section, staff_input_section, attachments):
    """Push strategy as attachment + stub description."""
    att_filename = STRATEGY_ATTACHMENT_TEMPLATE.format(issue_key=issue_key)

    with _attachment_writer_lock(issue_key):
        stub_md = _build_description_stub(
            existing_md, strategy_section, staff_input_section, att_filename)
        stub_adf = markdown_to_adf(stub_md)

        with tempfile.NamedTemporaryFile(
                mode="w", suffix=".md", delete=False, encoding="utf-8") as tmp:
            tmp.write(strategy_section + "\n")
            tmp_path = tmp.name
        try:
            add_attachment(server, user, token, issue_key,
                           tmp_path, filename=att_filename)
            update_description(server, user, token, issue_key, stub_adf)
        finally:
            os.unlink(tmp_path)

    print(f"OK: Strategy pushed to {issue_key} as attachment {att_filename}")


def main():
    parser = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("issue_key", help="RHAISTRAT issue key")
    parser.add_argument("local_file", help="Local strategy file path")
    args = parser.parse_args()

    server, user, token = require_env()
    if not all([server, user, token]):
        print("Error: JIRA_SERVER, JIRA_USER, and JIRA_TOKEN required.",
              file=sys.stderr)
        sys.exit(2)

    with open(args.local_file, "r", encoding="utf-8") as f:
        local_content = f.read()

    source_rfe = extract_source_rfe(local_content)
    local_title = extract_title(local_content)
    local_content = strip_metadata(local_content)

    strategy_section = extract_strategy_section(local_content)
    if not strategy_section:
        print("Error: no Strategy section found in local file.",
              file=sys.stderr)
        sys.exit(1)

    staff_input_section = extract_staff_input_section(local_content)

    issue = get_issue(server, user, token, args.issue_key,
                      fields=["description", "attachment", "summary"])
    existing_desc = issue.get("fields", {}).get("description")
    existing_md = adf_to_markdown(existing_desc).strip() if existing_desc else ""
    attachments = issue.get("fields", {}).get("attachment", [])
    current_summary = issue.get("fields", {}).get("summary", "") or ""

    if existing_md:
        backup_dir = os.path.join(os.path.dirname(args.local_file), "..", "strat-originals")
        os.makedirs(backup_dir, exist_ok=True)
        backup_path = os.path.join(backup_dir, f"{args.issue_key}-pre-push.md")
        if not os.path.exists(backup_path):
            with open(backup_path, "w", encoding="utf-8") as f:
                f.write(existing_md)
            print(f"Backed up existing description to {backup_path}", file=sys.stderr)

    if STRATEGY_HEADING in existing_md:
        updated_md = re.sub(
            r'## Strategy \(AI Generated by Agentic SDLC Pipeline\).*?(?=\n## (?!#)|$)',
            strategy_section + "\n",
            existing_md,
            flags=re.DOTALL,
        )
    else:
        updated_md = existing_md + "\n\n" + strategy_section

    if staff_input_section:
        if re.search(STAFF_INPUT_PATTERN, updated_md):
            updated_md = re.sub(
                STAFF_INPUT_PATTERN + r'.*?(?=\n## (?!#)|$)',
                staff_input_section + "\n",
                updated_md,
                flags=re.DOTALL,
            )
        else:
            updated_md = updated_md.rstrip() + "\n\n" + staff_input_section
    elif not re.search(STAFF_INPUT_PATTERN, updated_md):
        updated_md = updated_md.rstrip() + "\n\n" + STAFF_INPUT_TEMPLATE

    if source_rfe and STRATEGY_HEADING in updated_md:
        rfe_ref = build_rfe_reference(source_rfe, server)
        idx = updated_md.index(STRATEGY_HEADING)
        updated_md = rfe_ref + "\n\n" + updated_md[idx:]

    updated_adf = markdown_to_adf(updated_md)

    try:
        update_description(server, user, token, args.issue_key, updated_adf)
    except urllib.error.HTTPError as e:
        if e.code == 400:
            error_body = getattr(e, "error_body", "") or e.read().decode("utf-8", errors="replace")
            if "CONTENT_LIMIT_EXCEEDED" in error_body:
                adf_size = len(json.dumps(updated_adf))
                print(f"  Jira rejected description (CONTENT_LIMIT_EXCEEDED, "
                      f"{adf_size:,} chars ADF). Falling back to attachment.",
                      file=sys.stderr)
                _push_via_attachment(server, user, token, args.issue_key,
                                     updated_md, strategy_section,
                                     staff_input_section, attachments)
                return
        raise

    print(f"OK: Strategy and Staff Engineer / SME Input pushed to "
          f"{args.issue_key}")

    if local_title:
        new_summary = compute_synced_summary(current_summary, local_title)
        if new_summary is not None:
            update_summary(server, user, token, args.issue_key, new_summary)
            print(f"  Summary updated to match refined title: {new_summary}")


if __name__ == "__main__":
    main()
