#!/usr/bin/env python3
"""Push the AI-generated Strategy section to a RHAISTRAT issue in Jira.

Reads the existing Jira description (preserving human-authored content),
then appends or replaces the "## Strategy (AI Generated by Agentic SDLC
Pipeline)" section with the locally refined version.

Usage:
    python3 scripts/push_strategy.py RHAISTRAT-1520 artifacts/strat-tasks/RHAISTRAT-1520.md

Environment variables:
    JIRA_SERVER  Jira server URL
    JIRA_USER    Jira username/email
    JIRA_TOKEN   Jira API token
"""

import argparse
import json
import os
import re
import sys
import tempfile
import urllib.error

from jira_utils import (
    require_env,
    get_issue,
    adf_to_markdown,
    markdown_to_adf,
    api_call_with_retry,
    strip_metadata,
    add_attachment,
    delete_attachment,
)


STRATEGY_HEADING = "## Strategy (AI Generated by Agentic SDLC Pipeline)"
STAFF_INPUT_HEADING = "## Staff Engineer / SME Input"
STAFF_INPUT_PATTERN = r'## Staff Engineer(?: / SME)? Input'
STAFF_INPUT_TEMPLATE = """## Staff Engineer / SME Input

*Add technical corrections, architectural direction, component preferences, or domain expertise below. Write in declarative, cumulative form — statements that remain valid across refinement iterations. This input takes priority over architecture context when they conflict. After review: address findings, then remove the needs-attention label from Jira.*"""

STRATEGY_ATTACHMENT_TEMPLATE = "{issue_key}-strategy.md"
ATTACHMENT_NOTICE = (
    "> **Note:** The full strategy exceeds Jira's description size limit "
    "and is stored as an attachment: `{filename}`. "
    "The TL;DR is shown below for quick reference."
)
ATTACHMENT_NOTICE_NO_TLDR = (
    "> **Note:** The full strategy exceeds Jira's description size limit "
    "and is stored as an attachment: `{filename}`."
)


def extract_strategy_section(local_content):
    """Extract the Strategy section from a local strategy file."""
    match = re.search(
        r'(## Strategy \(AI Generated by Agentic SDLC Pipeline\).*?)(?=\n## (?!#)|$)',
        local_content,
        re.DOTALL,
    )
    if not match:
        return None
    return match.group(1).strip()


def extract_staff_input_section(local_content):
    """Extract the Staff Engineer / SME Input section from a local strategy file."""
    match = re.search(
        r'(' + STAFF_INPUT_PATTERN + r'.*?)(?=\n## (?!#)|$)',
        local_content,
        re.DOTALL,
    )
    if not match:
        return None
    return match.group(1).strip()


def extract_tldr_section(strategy_section):
    """Extract the ### TL;DR subsection from a strategy section."""
    match = re.search(
        r'(### TL;DR.*?)(?=\n### (?!#)|$)',
        strategy_section,
        re.DOTALL,
    )
    if not match:
        return None
    return match.group(1).strip()


def _build_description_stub(existing_md, strategy_section, staff_input_section,
                            attachment_filename):
    """Build a reduced description with TL;DR stub instead of full strategy."""
    if STRATEGY_HEADING in existing_md:
        before_strategy = existing_md[:existing_md.index(STRATEGY_HEADING)]
    else:
        before_strategy = existing_md

    # Remove any trailing Staff Engineer / SME Input from before_strategy
    # (it will be re-added at the end)
    staff_match = re.search(STAFF_INPUT_PATTERN, before_strategy)
    if staff_match:
        before_strategy = before_strategy[:staff_match.start()]

    tldr = extract_tldr_section(strategy_section)
    if tldr:
        notice = ATTACHMENT_NOTICE.format(filename=attachment_filename)
        stub_strategy = (
            f"{STRATEGY_HEADING}\n\n"
            f"{notice}\n\n"
            f"{tldr}\n"
        )
    else:
        notice = ATTACHMENT_NOTICE_NO_TLDR.format(filename=attachment_filename)
        stub_strategy = (
            f"{STRATEGY_HEADING}\n\n"
            f"{notice}\n"
        )

    parts = [before_strategy.rstrip()]
    parts.append(stub_strategy)

    if staff_input_section:
        parts.append(staff_input_section)
    elif not re.search(STAFF_INPUT_PATTERN, before_strategy):
        parts.append(STAFF_INPUT_TEMPLATE)

    return "\n\n".join(parts)


def update_description(server, user, token, issue_key, description_adf):
    """PUT only the description field (no summary change)."""
    body = {"fields": {"description": description_adf}}
    path = f"/issue/{issue_key}"
    api_call_with_retry(server, path, user, token, body=body, method="PUT")


def _find_strategy_attachment(attachments, issue_key):
    """Find an existing strategy attachment by naming convention."""
    filename = STRATEGY_ATTACHMENT_TEMPLATE.format(issue_key=issue_key)
    for att in attachments:
        if att.get("filename") == filename:
            return att
    return None


def _push_via_attachment(server, user, token, issue_key, existing_md,
                         strategy_section, staff_input_section, attachments):
    """Push strategy as attachment + stub description."""
    att_filename = STRATEGY_ATTACHMENT_TEMPLATE.format(issue_key=issue_key)

    stub_md = _build_description_stub(
        existing_md, strategy_section, staff_input_section, att_filename)
    stub_adf = markdown_to_adf(stub_md)
    update_description(server, user, token, issue_key, stub_adf)

    with tempfile.NamedTemporaryFile(
            mode="w", suffix=".md", delete=False, encoding="utf-8") as tmp:
        tmp.write(strategy_section + "\n")
        tmp_path = tmp.name
    try:
        old_att = _find_strategy_attachment(attachments, issue_key)
        if old_att:
            delete_attachment(server, user, token, old_att["id"])
        add_attachment(server, user, token, issue_key,
                       tmp_path, filename=att_filename)
    finally:
        os.unlink(tmp_path)

    print(f"OK: Strategy pushed to {issue_key} as attachment {att_filename}")


def main():
    parser = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("issue_key", help="RHAISTRAT issue key")
    parser.add_argument("local_file", help="Local strategy file path")
    args = parser.parse_args()

    server, user, token = require_env()
    if not all([server, user, token]):
        print("Error: JIRA_SERVER, JIRA_USER, and JIRA_TOKEN required.",
              file=sys.stderr)
        sys.exit(2)

    with open(args.local_file, "r", encoding="utf-8") as f:
        local_content = f.read()

    local_content = strip_metadata(local_content)

    strategy_section = extract_strategy_section(local_content)
    if not strategy_section:
        print("Error: no Strategy section found in local file.",
              file=sys.stderr)
        sys.exit(1)

    staff_input_section = extract_staff_input_section(local_content)

    issue = get_issue(server, user, token, args.issue_key,
                      fields=["description", "attachment"])
    existing_desc = issue.get("fields", {}).get("description")
    existing_md = adf_to_markdown(existing_desc).strip() if existing_desc else ""
    attachments = issue.get("fields", {}).get("attachment", [])

    if existing_md:
        backup_dir = os.path.join(os.path.dirname(args.local_file), "..", "strat-originals")
        os.makedirs(backup_dir, exist_ok=True)
        backup_path = os.path.join(backup_dir, f"{args.issue_key}-pre-push.md")
        if not os.path.exists(backup_path):
            with open(backup_path, "w", encoding="utf-8") as f:
                f.write(existing_md)
            print(f"Backed up existing description to {backup_path}", file=sys.stderr)

    if STRATEGY_HEADING in existing_md:
        updated_md = re.sub(
            r'## Strategy \(AI Generated by Agentic SDLC Pipeline\).*?(?=\n## (?!#)|$)',
            strategy_section + "\n",
            existing_md,
            flags=re.DOTALL,
        )
    else:
        updated_md = existing_md + "\n\n" + strategy_section

    if staff_input_section:
        if re.search(STAFF_INPUT_PATTERN, updated_md):
            updated_md = re.sub(
                STAFF_INPUT_PATTERN + r'.*?(?=\n## (?!#)|$)',
                staff_input_section + "\n",
                updated_md,
                flags=re.DOTALL,
            )
        else:
            updated_md = updated_md.rstrip() + "\n\n" + staff_input_section
    elif not re.search(STAFF_INPUT_PATTERN, updated_md):
        updated_md = updated_md.rstrip() + "\n\n" + STAFF_INPUT_TEMPLATE

    updated_adf = markdown_to_adf(updated_md)

    try:
        update_description(server, user, token, args.issue_key, updated_adf)
    except urllib.error.HTTPError as e:
        if e.code == 400:
            error_body = getattr(e, "error_body", "") or e.read().decode("utf-8", errors="replace")
            if "CONTENT_LIMIT_EXCEEDED" in error_body:
                adf_size = len(json.dumps(updated_adf))
                print(f"  Jira rejected description (CONTENT_LIMIT_EXCEEDED, "
                      f"{adf_size:,} chars ADF). Falling back to attachment.",
                      file=sys.stderr)
                _push_via_attachment(server, user, token, args.issue_key,
                                     existing_md, strategy_section,
                                     staff_input_section, attachments)
                return
        raise

    # Clean up orphan attachment if strategy now fits in description
    old_att = _find_strategy_attachment(attachments, args.issue_key)
    if old_att:
        delete_attachment(server, user, token, old_att["id"])
        print(f"  Removed previous strategy attachment "
              f"(content now fits in description)", file=sys.stderr)

    print(f"OK: Strategy and Staff Engineer / SME Input pushed to "
          f"{args.issue_key}")


if __name__ == "__main__":
    main()
