#!/usr/bin/env python3
"""Save strategy version snapshots and generate section-by-section HTML diffs.

Called by the refine skill after writing a strategy file (local mode only).
Each invocation saves the current file as the next version and, if a prior
version exists, generates a word-level HTML diff between the two.

Usage:
    python3 scripts/strategy_history.py save local/strat-tasks/RHAISTRAT-2162.md
"""

import argparse
import os
import re
import shutil
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.join(os.path.dirname(__file__)))

from artifact_utils import read_frontmatter, update_frontmatter
from diff_match_patch import diff_match_patch


STRATEGY_HEADING = "## Strategy (AI Generated by Agentic SDLC Pipeline)"

STRATEGY_SECTION_RE = re.compile(
    r'(' + re.escape(STRATEGY_HEADING) + r'.*?)(?=\n## (?!#)|$)',
    re.DOTALL,
)


def find_latest_version(history_dir):
    """Return the highest version number found in history_dir, or 0."""
    if not os.path.isdir(history_dir):
        return 0
    best = 0
    for name in os.listdir(history_dir):
        m = re.match(r'^v(\d+)\.md$', name)
        if m:
            best = max(best, int(m.group(1)))
    return best


def extract_strategy_section(content):
    """Extract the Strategy section from a strategy file."""
    match = STRATEGY_SECTION_RE.search(content)
    if not match:
        return None
    return match.group(1).strip()


def split_subsections(strategy_text):
    """Split a Strategy section into an ordered list of (heading, body) tuples.

    The first entry captures any text between the ## heading and the first ###.
    """
    parts = re.split(r'(?=^### )', strategy_text, flags=re.MULTILINE)
    result = []
    for part in parts:
        part = part.strip()
        if not part:
            continue
        heading_match = re.match(r'^(#{2,3}\s+.+?)$', part, re.MULTILINE)
        if heading_match:
            heading = heading_match.group(1).strip()
            body = part[heading_match.end():].strip()
        else:
            heading = ""
            body = part
        result.append((heading, body))
    return result


def word_diff(old_text, new_text):
    """Compute a word-level diff using diff-match-patch.

    Returns a list of (op, text) tuples where op is -1 (delete), 0 (equal),
    or 1 (insert).
    """
    dmp = diff_match_patch()
    diffs = dmp.diff_main(old_text, new_text)
    dmp.diff_cleanupSemantic(diffs)
    return diffs


def has_changes(diffs):
    """Return True if the diff list contains any inserts or deletes."""
    return any(op != 0 for op, _ in diffs)


def diff_to_html(diffs):
    """Convert a list of (op, text) diff tuples to inline HTML."""
    parts = []
    for op, text in diffs:
        escaped = escape_html(text)
        if op == 0:
            parts.append(escaped)
        elif op == -1:
            parts.append(f'<del class="diff-del">{escaped}</del>')
        elif op == 1:
            parts.append(f'<ins class="diff-ins">{escaped}</ins>')
    return "".join(parts)


def escape_html(text):
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def generate_diff_html(strat_id, old_version, new_version, old_content, new_content):
    """Generate a self-contained HTML diff between two strategy versions."""
    old_strategy = extract_strategy_section(old_content) or ""
    new_strategy = extract_strategy_section(new_content) or ""

    old_subs = split_subsections(old_strategy)
    new_subs = split_subsections(new_strategy)

    old_map = {h: b for h, b in old_subs}
    new_map = {h: b for h, b in new_subs}

    all_headings = []
    seen = set()
    for h, _ in old_subs + new_subs:
        if h not in seen:
            all_headings.append(h)
            seen.add(h)

    sections_html = []
    toc_entries = []
    changed_count = 0

    for i, heading in enumerate(all_headings):
        old_body = old_map.get(heading, "")
        new_body = new_map.get(heading, "")
        anchor = f"section-{i}"

        if heading == STRATEGY_HEADING:
            display_heading = "Strategy (Overview)"
        else:
            display_heading = heading.lstrip("# ").strip()

        diffs = word_diff(old_body, new_body)
        changed = has_changes(diffs)

        if heading not in old_map:
            changed = True
            diff_html = f'<div class="diff-content"><ins class="diff-ins">{escape_html(new_body)}</ins></div>'
        elif heading not in new_map:
            changed = True
            diff_html = f'<div class="diff-content"><del class="diff-del">{escape_html(old_body)}</del></div>'
        elif changed:
            diff_html = f'<div class="diff-content">{diff_to_html(diffs)}</div>'
        else:
            diff_html = '<div class="diff-content no-changes-body">No changes</div>'

        if changed:
            changed_count += 1

        status_class = "changed" if changed else "unchanged"
        collapsed = "" if changed else " collapsed"

        toc_entries.append(
            f'<li class="toc-{status_class}">'
            f'<a href="#{anchor}">{escape_html(display_heading)}</a>'
            f'<span class="toc-badge {status_class}">{"changed" if changed else "no changes"}</span>'
            f'</li>'
        )

        sections_html.append(
            f'<div class="section {status_class}{collapsed}" id="{anchor}">'
            f'<div class="section-header" onclick="toggleSection(this)">'
            f'<span class="collapse-icon">{"▼" if changed else "▶"}</span>'
            f'<span class="section-title">{escape_html(display_heading)}</span>'
            f'<span class="section-badge {status_class}">{"changed" if changed else "no changes"}</span>'
            f'</div>'
            f'{diff_html}'
            f'</div>'
        )

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    total = len(all_headings)
    unchanged_count = total - changed_count

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{escape_html(strat_id)} — v{old_version} → v{new_version}</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: #0d1117; color: #c9d1d9;
    max-width: 960px; margin: 0 auto; padding: 24px;
    line-height: 1.6;
}}
h1 {{ font-size: 1.4em; margin-bottom: 4px; }}
.subtitle {{ color: #8b949e; margin-bottom: 20px; font-size: 0.9em; }}
.summary {{
    background: #161b22; border: 1px solid #30363d; border-radius: 6px;
    padding: 12px 16px; margin-bottom: 20px; font-size: 0.9em;
}}
.summary .stat {{ display: inline-block; margin-right: 20px; }}
.stat-changed {{ color: #f0883e; }}
.stat-unchanged {{ color: #8b949e; }}
.toc {{
    background: #161b22; border: 1px solid #30363d; border-radius: 6px;
    padding: 12px 16px; margin-bottom: 24px;
}}
.toc h2 {{ font-size: 1em; margin-bottom: 8px; }}
.toc ul {{ list-style: none; }}
.toc li {{ padding: 3px 0; font-size: 0.9em; }}
.toc a {{ color: #58a6ff; text-decoration: none; }}
.toc a:hover {{ text-decoration: underline; }}
.toc-badge {{
    font-size: 0.75em; padding: 1px 6px; border-radius: 10px;
    margin-left: 8px; vertical-align: middle;
}}
.toc-badge.changed {{ background: #f0883e22; color: #f0883e; }}
.toc-badge.unchanged {{ background: #30363d; color: #8b949e; }}
.section {{
    background: #161b22; border: 1px solid #30363d; border-radius: 6px;
    margin-bottom: 12px; overflow: hidden;
}}
.section-header {{
    padding: 10px 16px; cursor: pointer; display: flex;
    align-items: center; gap: 8px; user-select: none;
}}
.section-header:hover {{ background: #1c2128; }}
.collapse-icon {{ font-size: 0.7em; width: 16px; text-align: center; color: #8b949e; }}
.section-title {{ flex: 1; font-weight: 600; }}
.section-badge {{
    font-size: 0.75em; padding: 1px 8px; border-radius: 10px;
}}
.section-badge.changed {{ background: #f0883e22; color: #f0883e; }}
.section-badge.unchanged {{ background: #30363d; color: #8b949e; }}
.diff-content {{
    padding: 12px 16px; border-top: 1px solid #30363d;
    white-space: pre-wrap; word-wrap: break-word; font-size: 0.9em;
}}
.no-changes-body {{ color: #484f58; font-style: italic; }}
.collapsed .diff-content {{ display: none; }}
.collapsed .collapse-icon {{ transform: rotate(0deg); }}
.diff-del {{
    background: rgba(248, 81, 73, 0.2); color: #f85149;
    text-decoration: line-through; padding: 1px 2px; border-radius: 3px;
}}
.diff-ins {{
    background: rgba(63, 185, 80, 0.2); color: #3fb950;
    text-decoration: none; padding: 1px 2px; border-radius: 3px;
}}
</style>
</head>
<body>
<h1>{escape_html(strat_id)} — Version Diff</h1>
<div class="subtitle">v{old_version} → v{new_version} &middot; {timestamp}</div>
<div class="summary">
    <span class="stat stat-changed">{changed_count} section{"s" if changed_count != 1 else ""} changed</span>
    <span class="stat stat-unchanged">{unchanged_count} section{"s" if unchanged_count != 1 else ""} unchanged</span>
</div>
<div class="toc">
    <h2>Sections</h2>
    <ul>
        {"".join(toc_entries)}
    </ul>
</div>
{"".join(sections_html)}
<script>
function toggleSection(header) {{
    header.parentElement.classList.toggle('collapsed');
    var icon = header.querySelector('.collapse-icon');
    icon.textContent = header.parentElement.classList.contains('collapsed') ? '▶' : '▼';
}}
</script>
</body>
</html>"""
    return html


def save(strategy_path):
    """Save a version snapshot and generate a diff if a prior version exists."""
    if not os.path.isfile(strategy_path):
        print(f"Error: file not found: {strategy_path}", file=sys.stderr)
        return 1

    data, _ = read_frontmatter(strategy_path)
    strat_id = data.get("strat_id")
    if not strat_id:
        strat_id = os.path.splitext(os.path.basename(strategy_path))[0]

    base_dir = os.path.dirname(strategy_path)
    history_dir = os.path.join(base_dir, "..", "strat-history", strat_id)
    history_dir = os.path.normpath(history_dir)
    os.makedirs(history_dir, exist_ok=True)

    current_version = find_latest_version(history_dir)
    new_version = current_version + 1

    with open(strategy_path, encoding="utf-8") as f:
        content = f.read()

    new_path = os.path.join(history_dir, f"v{new_version}.md")
    with open(new_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Saved {strat_id} v{new_version} to {new_path}", file=sys.stderr)

    if current_version >= 1:
        old_path = os.path.join(history_dir, f"v{current_version}.md")
        with open(old_path, encoding="utf-8") as f:
            old_content = f.read()

        diff_html = generate_diff_html(
            strat_id, current_version, new_version, old_content, content
        )

        diff_filename = f"v{current_version}-to-v{new_version}.html"
        diff_path = os.path.join(history_dir, diff_filename)
        with open(diff_path, "w", encoding="utf-8") as f:
            f.write(diff_html)

        relative_diff = os.path.join(
            "strat-history", strat_id, diff_filename
        )
        update_frontmatter(strategy_path, {"latest_diff": relative_diff}, "strat-task")

        print(f"Generated diff: {diff_path}", file=sys.stderr)

    return 0


def main():
    parser = argparse.ArgumentParser(
        description="Save strategy version snapshots and generate HTML diffs.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="command")
    save_parser = sub.add_parser("save", help="Save a version snapshot")
    save_parser.add_argument("strategy_file", help="Path to the strategy file")

    args = parser.parse_args()
    if args.command == "save":
        sys.exit(save(args.strategy_file))
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
